### ISSUE TITLE
[BUG/ISSUE] Retrieving files for a nested grid simulation

### ISSUE THREAD

**Issue by jdsouz** [geoschem/geos-chem#401] opened 2020-08-06 19:34 UTC
# Report a GEOS-Chem bug or technical issue

## Describe the bug:

I was running a nested grid simulation over India, and after yielding the boundary conditions through my first run, I could not access the boundary conditions files to input into the nested grid simulation. It seemed like GEOS-Chem was looking for 2015 Boundary Conditions, even though I had specified to look for 2018 files. 

### Expected behavior: ###

I expected GEOS-Chem to find my boundary conditions files and successfully run a nested grid simulation over India (50E to 100E, 10S to 50N)

### Actual behavior: ###

GEOS-Chem reported errors that it could not find my boundary conditions files through the HEMCO.log

### Steps to reproduce: the bug:

Ran boundary conditions, followed nested grid instructions on GEOS-Chem wiki, edited HISTORY.rc. 
However, when I was creating the boundary conditions, I did not set GC_BCs to true. I only changed this to true in my nested grid run. 

**Compilation commands**

1.  vi CopyRunDirs.input (edited run dates to 1/1/2018 to 6/1/2018, chose standard merra2_4x5)
2.  ./gcCopyRunDirs
3.  cd ~/GC/rundirs/merra2_4x5_standard/
4.  vi HISTORY.rc (changed frequency and duration of Aerosol, AerosolMass, and SpeciesConc. Also set boundary conditions)
5.  cp (other run directory)/a_run_geos_chem ~/GC/rundirs/merra2_4x5_standard

For the nested grid run, I went into HEMCO_Config.rc and:
6.  Set GC_BCs to true
7.  Changed directory to "BC_  (run directory)/GEOSChem.BoundaryConditions.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesBC"
8. Changed input.geos to boundary conditions dimensions.

**Run commands**

1.  load_if17
2.  make realclean
3.  make -j4 build
4.  sbatch (job number)

### Error messages

In slurm, these were the error messages:
```
GEOS-Chem ERROR: Error encountered in "HCO_Run"!
 -> at HCOI_GC_Run (in module GeosCore/hcoi_gc_main_mod.F90)

THIS ERROR ORIGINATED IN HEMCO!  Please check the HEMCO log file for
additional error messages!
===============================================================================
          owned by: jdsouza   dated: Mon Aug  3 23:31:04 2020
===============================================================================rundirs/merra2_4x5_standard/slurm-65945596.out
GEOS-Chem ERROR: Error encountered in "HCOI_GC_Run"!
 -> at Emissions_Run (in module GeosCore/emissions_mod.F90).harvard.edu
===============================================================================
While opening file "slurm-65945596.out"
===============================================================================
GEOS-CHEM ERROR: Error encountered in "Emissions_Run", Phase 0
(1) Another program may be editing the same file.  If this is the case,
This error can indicate a missing file. Please check the HEMCO log file for
additional error messages!es.  Quit, or continue with caution.
```

In HEMCO.log, these were the error messages:
```
HEMCO ERROR: Cannot find file for current simulation time: /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/GEOS_4x5/MERRA2/2015/01/MERRA2.20150101.CN.05x0625.nc4 - Cannot get field FRLAKE. Please check file name and time (incl. time range fl
ERROR LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error encountered in routine HCOIO_Read_Std!
ERROR LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error in HCOIO_DATAREAD called from HEMCO ReadList_Fill: FRLAKE
ERROR LOCATION: ReadList_Fill (HCO_ReadList_Mod.F90)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Error in ReadList_Fill (1) called from HEMCO ReadList_Read
ERROR LOCATION: ReadList_Read (HCO_ReadList_Mod.F90)
```

### Your GEOS-Chem version and runtime environment:

 - GEOS-Chem version: 12.8.2
 - Compiler version:
 - netCDF version:
 - netCDF-Fortran version (if applicable):
 - Did you run on a computational cluster, on the AWS cloud: No
   - If you ran on the AWS cloud, please specify the Amazon Machine Image (AMI) ID: __
 - Are you using GEOS-Chem "out of the box" (i.e. unmodified): Yes
   - If you have modified GEOS-Chem, please list what was changed: __

### Input and log files to attach

 - lastbuild: __
 - input.geos: __
 - HEMCO_Config.rc: __
 - GEOS-Chem "Classic" log file: __
 - HEMCO.log: __
 - slurm.out or any other error messages from your scheduler: __
 - Any other error messages: __

**Comment by yantosca** [comment] 2020-08-07 13:44
Thanks for writing. Double check the METDIR setting in the HEMCO_Config.rc file in your nested-grid run directory.  It may still be pointing to the 4x5 run directory.   You may have to change in your nested-grid run directory HEMCO_Config.rc:
```
METDIR:                      /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/GEOS_4x5/MERRA2
```
to
```
METDIR:                      /n/holyscratch01/external_repos/GEOS-CHEM/gcgrid/data/ExtData/GEOS_0.5x0.625/MERRA2
```
that may be the issue.

**Comment by jdsouz** [comment] 2020-08-08 04:41
Thank you for your helpful response! I tried changing the METDIR, and while that solved the directory issue, a new error popped up in HEMCO.log:
 ``` 
HEMCO ERROR: Cannot find file for current simulation time: /n/mcelroy_lab/jdsouza/GC/rundirs/merra_oldboundary/OutputDir/GEOSChem.BoundaryConditions.20180101_0000z.nc4 - 
Cannot get field BC_ACET. Please check file name and time (incl. time range flag) in
ERROR LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
ERROR LOCATION: HCOIO_DataRead (hcoio_dataread_mod.F90)
ERROR LOCATION: ReadList_Fill (hco_readlist_mod.F90)
ERROR LOCATION: ReadList_Read (hco_readlist_mod.F90)
ERROR LOCATION: HCO_RUN (hco_driver_mod.F90)
Species CFC12 
```

In this error, it seems that it can't find field BC_ACET, rather than the other error where it couldn't find field FRLAKE. Any ideas on how to resolve this?

**Comment by WilliamDowns** [comment] 2020-08-10 18:03
This error arises because HEMCO cannot find boundary conditions for the start of your nested grid run (0000z Jan 1st 2018). This is because a boundary conditions run that starts at 0000z Jan 1st 2018 will only produce boundary conditions for timesteps after 0000z. You can generate the corresponding conditions by running your boundary conditions simulation again for only Dec 31st 2017, which will generate a file with the timestamp 20180101_0000z containing boundary conditions only for 0000z Jan 1st 2018. 

You will then need to join this file with your existing file for Jan 1st (`GEOSChem.BoundaryConditions.20180101_0010z.nc4`), which can be done using the CDO utility (loaded with `module load intel/17.0.4-fasrc01 cdo/1.9.4-fasrc02` on Cannon). Execute the following commands from your `OutputDir` directory:
```
cdo mergetime GEOSChem.BoundaryConditions.20180101_0000z.nc4 GEOSChem.BoundaryConditions.20180101_0010z.nc4 NewGEOSChem.BoundaryConditions.20180101_0000z.nc4
mv NewGEOSChem.BoundaryConditions.20180101_0000z.nc4 GEOSChem.BoundaryConditions.20180101_0000z.nc4
```

This will generate the correct boundary conditions file with all of the proper timesteps. Thanks for pointing out this issue; this info is being added to the GEOS-Chem Wiki now.

**Comment by jdsouz** [comment] 2020-08-17 17:13
@yantosca @WilliamDowns Thank you all for your help thus far. I made the changes suggested and had some progress. My boundary conditions files now span from 12/31 to 6/1 and I changed the METDIR to GEOS_0.5x0.625. However, I am still getting some errors when running the simulation, which is shown in the slurm file below:

<img width="1105" alt="Screen Shot 2020-08-14 at 8 40 02 PM" src="https://user-images.githubusercontent.com/52765986/90423755-065c2700-e08b-11ea-8e67-521dd62f40b2.png">

I tried expanding the memory both in the interactive node and within a_run_geos_chem, but when I did that, the runs ended up getting stalled in the "pending" state on squeue, so I was never actually able to get the memory needed from the server to run the nested simulation. Can you assist me with this problem?

**Comment by yantosca** [comment] 2020-08-17 17:20
Hi @jdsouz.  It looks like the error may be that you didn't have enough memory specified.  The interactive nodes on Cannon I think only have a limited amount of memory available.  For a nested-grid run you might need #SBATCH --mem 60000 or higher, depending on the simulation type.

The pending message means that there aren't enough free cores/memory at the moment.  You can also try submitting to huce_cascasde on Cannon instead of huce_intel.  Usually that partition is much less occupied.

**Comment by jdsouz** [comment] 2020-08-17 18:32
Hi @yantosca Thank you for your message. I extended the memory to #SBATCH --mem 100000 and still received the same exact error message as above. I also tried running on huce_cascade and received the same error message. Any advice on how to remedy this?

**Comment by yantosca** [comment] 2020-08-18 20:26
HI @jdsouz.  You might want to reach out to FASRC for assistance.  Send them a copy of your run script when you open a ticket.

**Comment by jdsouz** [comment] 2020-08-19 18:09
Hi @yantosca I reached out to FASRC, fearing that I was experiencing a memory issue, and they responded with the following email (attached below). Do you have any more ideas on how to remedy this issue?

<img width="459" alt="Screen Shot 2020-08-19 at 2 06 07 PM" src="https://user-images.githubusercontent.com/52765986/90673106-38a18c00-e225-11ea-83f7-c00ae4a181cf.png">

**Comment by lizziel** [comment] 2020-08-19 18:23
Hi @jdsouz. Try rebuilding GEOS-Chem with debugging flags on, and then rerun to see if there is any additional information in the log. See the [GEOS-Chem wiki section on building with debug flags using Make](http://wiki.seas.harvard.edu/geos-chem/index.php/Debugging_GEOS-Chem#Recompile_GEOS-Chem_with_debug_options_turned_on).

The summary is you should do this during your build step:
make -j4 build DEBUG=yes FPE=yes TRACEBACK=yes BOUNDS=yes

Also, are there any errors in your HEMCO.log file?

**Comment by jdsouz** [comment] 2020-08-25 18:17
Hi @lizziel @yantosca thank you for all your help thus far. I added the "verbose" and "warnings" lines to the HEMCO_Config file and the simulation didn't work, but the slurm file changed slightly. I have attached the full file to this message, and I have screenshotted the segmentation fault that occurred on the slurm file below:

![Screen Shot 2020-08-25 at 2 14 48 PM](https://user-images.githubusercontent.com/52765986/91211807-57989600-e6dd-11ea-9910-2328aa9f84c4.png)

[slurm-642855.txt](https://github.com/geoschem/geos-chem/files/5125574/slurm-642855.txt)

Any idea on where to progress from here?

**Comment by jdsouz** [comment] 2020-08-25 18:50
I have also attached my HEMCO.log, if that is useful.

[HEMCO.log](https://github.com/geoschem/geos-chem/files/5125731/HEMCO.log)

**Comment by lizziel** [comment] 2020-08-25 19:01
Great, thanks. The log file reveals that the problem is regridding the 72-level STATE_PSC variables in the restart file to 47 levels. STATE_PSC has units 'count' so the code will hit the error for reasons I detailed above in my comment from 4 days ago. For context, I believe your comment from 39 minutes ago preceded that - not sure why it got moved up in the history.

I discussed this issue with @msulprizio, and she said users should use a 47-level restart file with 47-level nested grid simulations. In your case this will bypass the issue. Generally users also generate boundary conditions using the same number of levels as the number of levels they will ultimately run with. This is another reason this issue has never come up before.

**Comment by jdsouz** [comment] 2020-08-29 19:44
Hi @lizziel @yantosca thank you for all your help thus far. I changed my Restart, Boundary conditions, and nested grid input to 47 levels. While the previous error has been resolved, a new error has popped up when I try to run the 0.5x0.625 degree nested simulation. 

It seems that GEOS-Chem is not recognizing the 0.5x0.625 degree resolutions for some of the variables. I have pasted a screenshot of the slurm file error below, and I have linked both the slurm and HEMCO files to this message. Thank you for your continued help in this matter, and I look forward to finally fixing all the bugs in this simulation.

<img width="536" alt="Screen Shot 2020-08-29 at 3 41 43 PM" src="https://user-images.githubusercontent.com/52765986/91644869-29cd8d00-ea0e-11ea-861f-d888c24dd7e6.png">

[slurm-981970.txt](https://github.com/geoschem/geos-chem/files/5145920/slurm-981970.txt)

[HEMCO.log](https://github.com/geoschem/geos-chem/files/5145921/HEMCO.log)

**Comment by WilliamDowns** [comment] 2020-08-31 16:53
This is a known issue (see #329 ) that will be addressed with the release of GEOS-Chem 13.0.0. In the meantime, you can circumvent this issue by hardcoding the `UCXNETCDF` variable as `.FALSE.` by changing lines 106-108 of `GeosCore/ucx_mod.F90 to the following:

```Fortran
#else
  LOGICAL, PARAMETER            :: UCXNETCDF = .FALSE.  
#endif 
```

Remember to recompile before running again. Hope this helps.

**Comment by jdsouz** [comment] 2020-09-01 05:31
Hi @yantosca @WilliamDowns @lizziel thank you for your suggestions! The nested simulation ran without issues for a little over an hour before exiting with an error. I have attached the error message in the slurm file below. There are no anomalies with the HEMCO.log file. 

![Screen Shot 2020-09-01 at 1 28 21 AM](https://user-images.githubusercontent.com/52765986/91798240-75409080-ebf2-11ea-916e-902d6a12c889.png)

[slurm-1090228.txt](https://github.com/geoschem/geos-chem/files/5154121/slurm-1090228.txt)

Please let me know if you have any idea where this error is arising from or if you need more information from me. Thank you again for your continued support!

**Comment by WilliamDowns** [comment] 2020-09-01 14:27
Based on your previous responses, is your run directory somewhere in your home directory on Cannon (i.e. `~/.../rundir`)? I personally occasionally encounter an error in my home directory where the model cannot create the `OutputDir` folder for writing out diagnostics, generating the same "cannot create" file error. Could you manually create the `OutputDir` folder if it doesn't already exist, and then resubmit your run? If it already exists just let me know and we can look at other possible causes.

**Comment by jdsouz** [comment] 2020-09-01 20:40
That seemed to fix it!! Thank you so much for everyone's help in this weeks-long process!

**Comment by WilliamDowns** [comment] 2020-09-02 14:07
Great to hear! I am closing this issue now, feel free to open another if you run into any more trouble.

**Closed by WilliamDowns** 2020-09-02 14:07 UTC
Labels: FlexGrid, HEMCO, bug
