### ISSUE TITLE
[QUESTION] How to fix known RRTMG bugs in GC12.9.3?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#481] opened 2020-10-13 16:04 UTC
Hi there,

Following @msulprizio [hint](https://github.com/geoschem/geos-chem/issues/480), I read your [RRTMG fixes for GEOS-Chem 13.0.0](https://github.com/geoschem/geos-chem/issues/350). But before GC 13.0.0 is released, I'd like stick to GC 12.9.3 for RRTMG simulation. Therefore, I should at least make some code modifications to GC 12.9.3 to overcome some of the known issues. These include:
1) [Fix bug in RRTMG with stratospheric aerosol](https://github.com/geoschem/geos-chem/pull/347) by following code changes [here](https://github.com/geoschem/geos-chem/commit/b39d6cbdbf72867e2894230999977f0605528a61)
2) Fix [Seg fault in RRTMG when using Intel compiler if nitrates (NI) output enabled](https://github.com/geoschem/geos-chem/issues/438) by following code changes [here](https://github.com/geoschem/geos-chem/commit/2f5087e27cdfc841b44ff109369f74110751ee8b)
3) Beware that currently `RadAllSkyLWTOA_PM` actually denotes `RadAllSkyLWTOA_NOPM`, and the like

However, I did not find corresponding code changes for the ***True “bugs” in RRTMG code*** described [here](https://github.com/geoschem/geos-chem/issues/350), which I believe is also necessary for my simulation. Could you please give me some hints? If I can see codes changes like in 1) and 2) that would be excellent!

BTW, does the 5th update described in the second-to-last comment [here](https://github.com/geoschem/geos-chem/issues/350) matter too much?

Personally I feel this question might be appropriate for @lizziel . Thanks in advance for any help!

**Comment by lizziel** [comment] 2020-10-13 18:17
Hi @FeiYao-Edinburgh,

The code updates are dispersed throughout our dev/13.0.0 branch but you should be able to adapt them fairly easily by looking at the code changes, especially a commit I made for use with GCHP that consolidated all updates that had come before. Assuming you are all set with 1 and 2 that you list, here is the commit that contains changes for 3, which is the main cause of differences between the binary and netcdf RRTMG diagnostics in GEOS-Chem 12. 
[commit f587bc2d](https://github.com/geoschem/geos-chem/commit/f587bc2d0a0a1fdadcda379c9188d5d337408a4f) ("Updates for RRTMG negcdf diagnostics in GEOS-Chem")

You can ignore the files in the `Interfaces/GCHP` and `run/GCHPctm` folders if you are using GEOS-Chem Classic.

You may also need updates in [commit 9eb68c3d](https://github.com/geoschem/geos-chem/commit/9eb68c3d31f9fc57c3d16506a20de43d6731516f) which contains modifications for the GC-Classic HISTORY.rc file.

Finally, there was another update to make the binary and netcdf match by shifting the RRTMG call time to the first timestep rather than the middle of the radiation timestep. Changes for that update are in commit https://github.com/geoschem/geos-chem/commit/408d4b37a348fa1c3db304963c910a8a7417257a.

**Comment by FeiYao-Edinburgh** [comment] 2020-10-13 18:50
Hi @lizziel 

Many thanks for your reply. I can basically understand commits [f587bc2d](https://github.com/geoschem/geos-chem/commit/f587bc2d0a0a1fdadcda379c9188d5d337408a4f) and [9eb68c3d](https://github.com/geoschem/geos-chem/commit/9eb68c3d31f9fc57c3d16506a20de43d6731516f) are for addressing 3. Commit [408d4bc](https://github.com/geoschem/geos-chem/commit/408d4b37a348fa1c3db304963c910a8a7417257a) is mainly for the 5th update you described [here](https://github.com/geoschem/geos-chem/issues/350). But I also mentioned **TrueTrue “bugs” in RRTMG code** described by @sdeastham also in this [page](https://github.com/geoschem/geos-chem/issues/350) (copied to below for your convenience). Can this issue also be solved following the three commit links you provided? Or is there another commit link for this?

I will complete this work asap and let you know when I succeed!

```
True “bugs” in RRTMG code
I discovered one genuine bug in the RRTMG code, which I believe crept in when we went from 1-D (“CSPEC”-style) indexing to
 3-D (“STT”-style) indexing. This was causing any aerosol in the stratosphere to have incorrect single scattering albedos and 
asymmetry parameters, which would then mess up fluxes beneath those layers as well. The fix to this is simple (extending a 
couple of arithmetic calculations to all grid boxes, rather than restricting it to lower grid cells). I’ve provided the fix (which comes 
down to deleting 6 lines) to the GCST as a pull request on GitHub. This bug would affect both BPCH and NetCDF diagnostics.

With that fixed, I believe that RRTMG should now be working perfectly in GEOS-Chem Classic with NetCDF diagnostics. I should 
note that it currently looks like the NetCDF diagnostics only put out fluxes, so SSA and asymmetry parameters are not output. 
This should be relatively straightforward to fix, though.
```

**Comment by lizziel** [comment] 2020-10-13 20:09
The fix for the bug in stratosphere is on the GitHub page for PR https://github.com/geoschem/geos-chem/pull/347. See the "Commit" tab on that page for the file diffs. It should be changes to one file only, `GeosCore/rrtmg_rad_transfer_mod.F90`.

That plus the commits I provided should give complete coverage for the GEOS-Chem Classic updates. But let me know if you run into any problems.

**Comment by FeiYao-Edinburgh** [comment] 2020-10-13 20:18
Ah I just realize **True “bugs” in RRTMG code** described [here](https://github.com/geoschem/geos-chem/issues/350) is exactly the stratospheric aerosol issue that corresponds to 1.

Up to now I am all set with 1 and 2. I will following your hints to address 3 and 4(shifting the RRTMG call time) soon. Once all set I will update here to let you know this issue can be closed. Many thanks for your continuous support!

**Comment by lizziel** [comment] 2020-10-13 20:51
Okay, great. I will close this issue but feel free to reopen if you run into problems.

**Comment by FeiYao-Edinburgh** [comment] 2020-10-14 19:29
> [commit f587bc2d](https://github.com/geoschem/geos-chem/commit/f587bc2d0a0a1fdadcda379c9188d5d337408a4f) ("Updates for RRTMG negcdf diagnostics in GEOS-Chem")

This commit targeting 3 indeed consolidates most but not complete updates that had come before. I add two more minor points below 1) expecting your confirmation; 2) for possible interest of other users who want to use GC12.9.3 to run RRTMG to archive correct netCDF diagnostics as will be done in 13.0.0.

1. When compiling, GC will complain `State_Chm%RRTMG_iSeed, State_Chm%RRTMG_iCld` if only making changes informed by [commit f587bc2d](https://github.com/geoschem/geos-chem/commit/f587bc2d0a0a1fdadcda379c9188d5d337408a4f). This bug can be easily fixed by doing additional changes following this [hint](https://github.com/geoschem/geos-chem/commit/fbb595ad6c43c8cb0cda11ae89e679f808e39895#diff-4e80a936162b901631692636f7082bad20262959a90f7f9710645a56f701bb24). As I compile successfully with this additional change, I think no more other changes are needed?
2. I found two lines of `State_Diag%Archive_RadOptics                   = .FALSE.` in `state_diag_mod.F90`. This won't impact anything but we can for sure remove one.

**Comment by lizziel** [comment] 2020-10-14 19:52
1. Yes, those fields need to exist in state_chm. They came in with a pull request from S. Eastham for RRTMG in GCHP.
2. The duplicate initialization was removed in a later commit within dev/13.0.0.

**Comment by lizziel** [comment] 2020-10-15 17:28
I am closing this issue again since it sounds like you now have it working. You should be able to reopen if needed, but I'll check that that is the case after this is closed.

**Comment by lizziel** [comment] 2020-10-15 17:43
Hi @FeiYao-Edinburgh, it turns out that GitHub does not allow users to reopen issues closed by repository collaborators such as myself. However, if an issue is closed you can still comment in the thread and we on the Support Team will still get notified. Please add a comment here if you have further issues with implementing RRTMG updates into 12.9.3.

**Comment by FeiYao-Edinburgh** [comment] 2020-10-16 15:07
Hi @lizziel , I have followed all the commits to address issues 1-4. The model compiles successfully. It is also running smoothly. However, I have difficulty with diagnostics collections. For example, if I run from `20160701 000000` to `20160703 000000` and do the following collections:
```
  Restart.filename:           './GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4',
  Restart.format:             'CFIO',
  Restart.frequency:          'End',
  Restart.duration:           'End',
  Restart.mode:               'instantaneous'

  Aerosols.template:          '%y4%m2%d2_%h2%n2z.nc4',
  Aerosols.format:            'CFIO',
  Aerosols.frequency:         00000000 030000
  Aerosols.duration:          00000001 000000
  Aerosols.mode:              'time-averaged'  

  RRTMG.template:             '%y4%m2%d2_%h2%n2z.nc4',
  RRTMG.format:               'CFIO',
  RRTMG.frequency:            00000000 030000
  RRTMG.duration:             00000001 000000
  RRTMG.mode:                 'time-averaged'

  StateMet.template:          '%y4%m2%d2_%h2%n2z.nc4',
  StateMet.format:            'CFIO',
  StateMet.frequency:         00000000 030000
  StateMet.duration:          00000001 000000
  StateMet.mode:              'time-averaged'
```
I will not be able to collect correct GEOSChem.Restart files as you can see the file size is at least incorrect. Also I will encounter error when using this Restart file to continue the model run say for `20160703 000000` to `20160705 000000`.
```
464K Oct 16 15:52 GEOSChem.Restart.20160703_0000z.nc4
```
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In Ncrd_3d_R4 #2:  NetCDF: Index exceeds dimension bound
     65536       286

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90)

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Meanwhile, I found other diagnostics are incorrect at least on the END simulation date according to their size information.
![image](https://user-images.githubusercontent.com/43779303/96275350-876f6600-0fc9-11eb-8484-11260f67f8a9.png)

I feel I must be missing some more but common changes since this issue applies to all diagnostics collections. I'd be grateful for your further help!

**Comment by FeiYao-Edinburgh** [comment] 2020-10-16 15:26
Checking the `GEOSChem.RRTMG.20160701_0000z.nc4` (`GEOSChem.RRTMG.20160702_0000z.nc4` is unable to open), I also found that RadAODWL1_?RRTMG? are all zeros (see below for instance, left plot is from Aerosols diagnostics while the right plot from RRTMG diagnostics). This means they have not been correctly assigned during RRTMG simulation. Personally I would feel that it is caused by following this [commit](https://github.com/geoschem/geos-chem/commit/408d4b37a348fa1c3db304963c910a8a7417257a), simply because it removes too many assignments but not adds corresponding ones?

![image](https://user-images.githubusercontent.com/43779303/96277530-4d539380-0fcc-11eb-8b87-4eb1c284aa5e.png)

**Comment by lizziel** [comment] 2020-10-16 16:28
Hi @FeiYao-Edinburgh, if your run crashed during file write then that would explain why the day 2 diagnostics files are so small. I suggest checking to see which collection is causing the fail by commenting out collections in `HISTORY.rc`. If the collection that is causing the problem is `Restart` or another collection that is not RRTMG then this issue may be unrelated to your RRTMG updates. You can check this by building an out-of-the-box 12.9.3 simulation and using the same run directory settings you are using now.

Regarding zero values in RadAOD, try adding prints within `GeosCore/rrtmg_rad_transfer_mod.F90` where the State_Diag array for RadAOD wavelength 1 is set to make sure the logic is executed properly. Also try not using the wildcard in `HISTORY.rc` to see if that has any impact.

**Comment by FeiYao-Edinburgh** [comment] 2020-10-16 18:33
Hi @lizziel 

1. I have run a tropchem simulation from 20160701 to 20160703 using the geos compiled from the modified codes. All collections including Restart, Aerosols, StateMet are correctly archived on all days. Hence I suppose the problem still lies in RRTMG updates. Below I summarize all the updates I have made based on GC12.9.3.
1.1 modify [GeosCore/rrtmg_rad_transfer_mod.F90](https://github.com/geoschem/geos-chem/commit/b39d6cbdbf72867e2894230999977f0605528a61)
1.2 modify [GeosCore/rrtmg_rad_transfer_mod.F90](https://github.com/geoschem/geos-chem/commit/2f5087e27cdfc841b44ff109369f74110751ee8b)
1.3 modify [GeosCore/main.F90, GeosCore/rrtmg_rad_transfer_mod.F90, Headers/diaglist_mod.F90, Headers/state_diag_mod.F90](https://github.com/geoschem/geos-chem/commit/f587bc2d0a0a1fdadcda379c9188d5d337408a4f)
1.4 modify [Headers/state_chm_mod.F90](https://github.com/geoschem/geos-chem/commit/fbb595ad6c43c8cb0cda11ae89e679f808e39895#diff-4e80a936162b901631692636f7082bad20262959a90f7f9710645a56f701bb24)
1.5 modify [GeosCore/main.F90, GeosCore/rrtmg_rad_transfer_mod.F90](https://github.com/geoschem/geos-chem/commit/408d4b37a348fa1c3db304963c910a8a7417257a)
I have checked all of these again and believe I have made all correct changes. So feel unsure where is the problem.

2. My RRTMG collection setting is as below (no ?RRTMG? and with BASE first)
```
  RRTMG.template:             '%y4%m2%d2_%h2%n2z.nc4',
  RRTMG.format:               'CFIO',
  RRTMG.frequency:            00000000 030000
  RRTMG.duration:             00000001 000000
  RRTMG.mode:                 'time-averaged'
  RRTMG.fields:               'RadClrSkySWSurf_BASE          ', 'GIGCchem',
                              'RadAllSkySWSurf_BASE          ', 'GIGCchem',
                              'RadAllSkySWSurf_PM            ', 'GIGCchem',
                              'RadAODWL1_SU                  ', 'GIGCchem',
                              'RadAODWL1_NI                  ', 'GIGCchem',
                              'RadAODWL1_AM                  ', 'GIGCchem',
                              'RadAODWL1_BC                  ', 'GIGCchem',
                              'RadAODWL1_OA                  ', 'GIGCchem',
                              'RadAODWL1_SS                  ', 'GIGCchem',
                              'RadAODWL1_DU                  ', 'GIGCchem',
                              'RadAODWL1_PM                  ', 'GIGCchem',
```
I have checked that `State_Diag%RADAODWL1(I,J,OUTIDX) = AODOUT` was executed so no problem with many if evaluations. But I found `AODOUT` are generally close to zeros like below. I feel this might be the problem but do not know how to address it. Personally, I feel at least AOD spatial pattern collected from RRTMG should confirm with those collected from Aerosols.
```
  1.3063893E-03
  9.6710376E-04
```

**Comment by FeiYao-Edinburgh** [comment] 2020-10-16 18:44
> AODOUT

Using grep to search and I found AODOUT is a local variable defined and used in GeosCore/rrtmg_rad_transfer_mod.F90. All related codes around AODOUT in my rrtmg_rad_transfer_mod.F90 are identical to [yours](https://github.com/geoschem/geos-chem/blob/dev/13.0.0/GeosCore/rrtmg_rad_transfer_mod.F90). This further makes it difficult for me to identify the problem.

**Comment by lizziel** [comment] 2020-10-16 19:19
Another you can do is plot your values and compare them to our [validation plots](http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/RRTMG_diagnostics/24hrAvg/day1/gcc_nc_unscaled_vs_bpch_time-shifted.pdf) for the binary versus netcdf diagnostics. If they are far off from these then there is something wrong. Note that these plots used 24-hour averages.

**Comment by FeiYao-Edinburgh** [comment] 2020-10-17 12:14
> Another thing you can do is plot your values and compare them to our [validation plots](http://ftp.as.harvard.edu/gcgrid/geos-chem/validation/RRTMG_diagnostics/24hrAvg/day1/gcc_nc_unscaled_vs_bpch_time-shifted.pdf) for the binary versus netcdf diagnostics

Hi @lizziel thanks for this! I have compared my results with this one and found similar daily spatial patterns regarding RadFlux but not RadAOD (mine are all zeros), say below as an instance.
![image](https://user-images.githubusercontent.com/43779303/96336750-fe643780-1079-11eb-833f-f1e0af1d19ff.png)
![image](https://user-images.githubusercontent.com/43779303/96336755-0623dc00-107a-11eb-9adb-51f0e4f3d201.png)

Meanwhile, I still cannot obtain the correct diagnostics on the END simulation date. This is found with steps 1.1-1.5 or 1.1-1.4 (I will check more). Below I provide you the error message when close to the end of simulation. You might be able to give me some further hints using these info.
```
===============================================================================
 Mass-Weighted OH Concentration
 Mean OH =    13.6402941324198       [1e5 molec/cm3]
===============================================================================
*** Error in `./geos': free(): invalid next size (normal): 0x0000000014adcff0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81299)[0x2b4fccb20299]
/geos/usrgeos/intel/Compiler/xe2016/compilers_and_libraries_2016.0.109/linux/compiler/lib/intel64_lin/libifcoremt.so.5(for_deallocate+0x12e)[0x2b4fca72dede]
./geos[0x12513ac]
./geos[0x406b45]
./geos[0x403a8e]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2b4fccac1555]
./geos[0x403999]
======= Memory map: ========
00400000-017ed000 r-xp 00000000 00:41 249957753                          /geos/d21/s1855106/GC.12.9.3/merra2_2x25_RRTMG/geos
019ed000-019ee000 r--p 013ed000 00:41 249957753                          /geos/d21/s1855106/GC.12.9.3/merra2_2x25_RRTMG/geos
019ee000-01b0f000 rw-p 013ee000 00:41 249957753                          /geos/d21/s1855106/GC.12.9.3/merra2_2x25_RRTMG/geos
01b0f000-08567000 rw-p 00000000 00:00 0
09ef1000-124f6a000 rw-p 00000000 00:00 0                                 [heap]
2b4fc6be4000-2b4fc6c06000 r-xp 00000000 08:31 1049311                    /usr/lib64/ld-2.17.so
2b4fc6c06000-2b4fc6c50000 rw-p 00000000 00:00 0
2b4fc6c53000-2b4fc6d13000 rw-p 00000000 00:00 0
2b4fc6d13000-2b4fc6d14000 ---p 00000000 00:00 0
2b4fc6d14000-2b4fc6d24000 rw-p 00000000 00:00 0
2b4fc6e05000-2b4fc6e06000 r--p 00021000 08:31 1049311                    /usr/lib64/ld-2.17.so
2b4fc6e06000-2b4fc6e07000 rw-p 00022000 08:31 1049311                    /usr/lib64/ld-2.17.so
2b4fc6e07000-2b4fc6e08000 rw-p 00000000 00:00 0
2b4fc6e08000-2b4fc6e73000 r-xp 00000000 08:31 1082877                    /usr/lib64/libnetcdff.so.5.3.1
2b4fc6e73000-2b4fc7072000 ---p 0006b000 08:31 1082877                    /usr/lib64/libnetcdff.so.5.3.1
2b4fc7072000-2b4fc7073000 r--p 0006a000 08:31 1082877                    /usr/lib64/libnetcdff.so.5.3.1
2b4fc7073000-2b4fc7074000 rw-p 0006b000 08:31 1082877                    /usr/lib64/libnetcdff.so.5.3.1
2b4fc7074000-2b4fc71d9000 r-xp 00000000 08:31 1082760                    /usr/lib64/libnetcdf.so.7.2.0
2b4fc71d9000-2b4fc73d8000 ---p 00165000 08:31 1082760                    /usr/lib64/libnetcdf.so.7.2.0
2b4fc73d8000-2b4fc7427000 r--p 00164000 08:31 1082760                    /usr/lib64/libnetcdf.so.7.2.0
2b4fc7427000-2b4fc742c000 rw-p 001b3000 08:31 1082760                    /usr/lib64/libnetcdf.so.7.2.0
2b4fc742c000-2b4fca465000 rw-p 00000000 00:00 0
2b4fca465000-2b4fca48b000 r-xp 00000000 00:40 262645                     /geos/usrgeos/intel/Compiler/xe2016/compilers_and_libraries_2016.0.109/linux/compiler/lib/intel64_lin/libifport.so.5
2b4fca48b000-2b4fca68b000 ---p 00026000 00:40 262645                     /geos/usrgeos/intel/Compiler/xe2016/compilers_and_libraries_2016.0.109/linux/compiler/lib/intel64_lin/libifport.so.5
2b4fca68b000-2b4fca68c000 r--p 00026000 00:40 262645                     /geos/usrgeos/intel/Compiler/xe2016/compilers_and_libraries_2016.0.109/linux/compiler/lib/intel64_lin/libifport.so.5
2b4fca68c000-2b4fca68e000 rw-p 00027000 00:40 262645                     /geos/usrgeos/intel/Compiler/xe2016/compilers_and_libraries_2016.0.109/linux/compiler/lib/intel64_lin/libifport.so.5
2b4fca68e000-2b4fca694000 rw-p 00000000 00:00 0
2b4fca694000-2b4fca7d9000 r-xp 00000000 00:40 262641                     /geos/usrgeos/intel/Compiler/xe2016/compilers_and_libraries_2016.0.109/linux/compiler/lib/intel64_lin/libifcoremt.so.
5
2b4fca7d9000-2b4fca9d8000 ---p 00145000 00:40 262641                     /geos/usrgeos/intel/Compiler/xe2016/compilers_and_libraries_2016.0.109/linux/compiler/lib/intel64_lin/libifcoremt.so.
5
2b4fca9d8000-2b4fca9db000 r--p 00144000 00:40 262641                     /geos/usrgeos/intel/Compiler/xe2016/compilers_and_libraries_2016.0.109/linux/compiler/lib/intel64_lin/libifcoremt.so.
5
2b4fca9db000-2b4fca9de000 rw-p 00147000 00:40 262641                     /geos/usrgeos/intel/Compiler/xe2016/compilers_and_libraries_2016.0.109/linux/compiler/lib/intel64_lin/libifcoremt.so.
5
2b4fca9de000-2b4fcaa26000 rw-p 00000000 00:00 0
```

**Comment by FeiYao-Edinburgh** [comment] 2020-10-17 14:58
> I will check more

Later on I roll back the codes to an earlier version with only modifications 1.1 and 1.2. As such I overcome the incomplete diagnostics on the END simulation date. Thus I can confirm the problem of incomplete diagnostics on the END simulation date was due to modification of 1.3. Only including 1.1 and 1.2 will only return me RadFlux diagnostics that should be interpreted with caution like below.
![image](https://user-images.githubusercontent.com/43779303/96342038-3cb92100-1091-11eb-9443-78a6b4068f89.png)

So up to now, I am still experiencing 1) incomplete diagnostics on the END simulation date; 2) zero RadAOD diagnostics. They are both due to [modifications in 1.3](https://github.com/geoschem/geos-chem/commit/f587bc2d0a0a1fdadcda379c9188d5d337408a4f). I also provide the error info above for you to help me check where the bug might occur. I expect and thanks for your further support.

**Comment by lizziel** [comment] 2020-10-19 14:57
Hi @FeiYao-Edinburgh, the release candidate for 13.0.0 will be released within the next few weeks. I suggest that you upgrade to that version to use RRTMG netcdf diagnostics if you have not been able to get them to work in 12.9.3.

While we do not support the recent RRTMG diagnostics updates in GEOS-Chem 12 you can try to figure out the issues with your updates by going through all debugging recommendations listed on our [Debugging GEOS-Chem wiki page](http://wiki.seas.harvard.edu/geos-chem/index.php/Debugging_GEOS-Chem).

**Comment by FeiYao-Edinburgh** [comment] 2020-10-19 15:07
Hi @lizziel Okay. I think I will discard steps 1.3-1.5 and run small, sample RRTMG simulations in GC.12.9.3 for my research design. I will bear in mind that PM denotes NOPM and the like. Also I will collect speciated AOD via Aerosols diagnostics. For this, may I ask what's the difference between AOD calculated via Aerosols and RRTMG diagnostics? They intend to be the same, right? Once you release 13.0.0, I will upgrade to it for my large, real RRTMG run.

**Comment by lizziel** [comment] 2020-10-19 15:11
Hi @FeiYao-Edinburgh, I do not think the Aerosols and RRTMG diagnostics are meant to be the same. However, I am not sure of the expected differences. @sdeastham, who has looked extensively at the RRTMG diagnostics, may be able to comment better on this.

**Comment by sdeastham** [comment] 2020-10-19 15:14
I'm afraid it's been too long since I looked at them to remember, but I agree they may well be different - I believe they use different optical properties. I'm not at all sure though and you'd need to investigate the code to be certain. What *is* certain is that they will differ because the RRTMG diagnostics are only going to be calculated when RRTMG is run.

**Comment by FeiYao-Edinburgh** [comment] 2020-10-19 15:19
Thank you! In this sense, using AOD from RRTMG diagnostics to interpret Radiation Flux from RRTMG diagnostics sounds more reasonable. I will keep an eye on your release of 13.0.0. Please feel free to close this issue now.

**Closed** 2020-10-19 15:20 UTC
Labels: question
