### ISSUE TITLE
[BUG/ISSUE]How to address this issue "WARNING: Negative concentration for species NO at (I,J,L)"?

### ISSUE THREAD

**Issue by Weiyanghu-NJU** [geoschem/geos-chem#1201] opened 2022-04-01 06:14 UTC
GCClassic fullchem simulation crash due to the negative NO concentration. 
I noticed "State_Chm%Species(I,J,L,N) = MAX(State_Chm%Species(I,J,L,N),0.0_fp)" in mixing_mod.F90 of  v12  to prevent negative concentrations, I wonder is it ok to add the above mentioned codes in v13?

VERSION:

GCClassic version: 13.3.3
GEOS-Chem version: 13.3.3
HEMCO version: 3.0.0
```console
Min and Max of each species in BC file [mol/mol]:
GET_BOUNDARY_CONDITIONS: Done applying BCs at 2016/12/01 06:00
 WARNING: Negative concentration for species NO at (I,J,L) =          143
         129          10
 WARNING: Negative concentration for species NO at (I,J,L) =          143
         129          11
 WARNING: Negative concentration for species NO at (I,J,L) =          143
         129          12
 WARNING: Negative concentration for species NO at (I,J,L) =          143
.
.
.
.
WARNING: Negative concentration for species NO at (I,J,L) =          143
         128          44
 WARNING: Negative concentration for species NO at (I,J,L) =          143
         128          45
 WARNING: Negative concentration for species NO at (I,J,L) =          143
         128          46
===============================================================================
GEOS-Chem ERROR:
 -> at DO_TEND (in module GeosCore/mixing_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountred in "DO_TEND"!
 -> at DO_MIXING (in module GeosCore/mixing_mod.F90)
```

**Comment by yantosca** [comment] 2022-04-01 12:52
Please see issues #1138, #969, #734, and #584 for some workarounds.

**Comment by yantosca** [comment] 2022-04-07 18:40
I will close out this issue as it is a duplicate of the above-mentioned issues.  Feel free to contact us again if you are still having problems.

**Closed by yantosca** 2022-04-07 18:40 UTC
Labels: bug, duplicate
