### ISSUE TITLE
[QUESTION] Does compiler impact simulations?

### ISSUE THREAD

**Issue by FeiYao-Edinburgh** [geoschem/geos-chem#638] opened 2021-03-02 11:40 UTC
Hi GCST,

I have a long-term GEOS-Chem job compiled by "ifort" running on our local sever. Recently our IT want to replace the OS of the server from the Scientific Linux to Ubuntu. As such the compiler "ifort" won't be installed there due to some optimization issues. Hence, I would like to ask will changing the compiler in the middle of a long-term simulation impact the consistence of that simulation? In other words, for the same settings of simulations, will there be large difference in the simulations by using different compilers (e.g. "ifort" vs "gfortran")? Or should there be just numerical noises?

Many thanks,
Fei

**Comment by yantosca** [comment] 2021-03-02 15:40
Thanks @FeiYao-Edinburgh for writing.  A while back we did a comparison between gfortran and ifort with v11-02a.  The results showed that the differences in output were very small, at the level of numerical noise.

http://wiki.seas.harvard.edu/geos-chem/index.php/GNU_Fortran_compiler#Results_from_the_v11-02a_1-month_benchmark_comparing_ifort_and_gfortran

I believe that is true today. The gfortran compiler will execute more slowly than ifort because it cannot take advantage of Intel-specific chipset optimizations.  But the output shouldn't change significantly.

One benefit: I have found that the gfortran compilers employ stricter parsing than ifort.  So you are more liable to find errors with gfortran than with ifort, especially dealing with code that deviates from the Fortran standard.  I do pretty much all of my development in Gfortran with that reason.

**Comment by FeiYao-Edinburgh** [comment] 2021-03-02 16:01
Thanks for your reply! I am all set!

**Comment by yantosca** [comment] 2021-03-02 16:04
Thanks @FeiYao-Edinburgh.  I'll close this out.

**Closed by yantosca** 2021-03-02 16:04 UTC
Labels: build, question

**Comment by FeiYao-Edinburgh** [comment] 2021-03-29 20:37
Following the discussion here, I would also like to inquiry whether the OS (e.g. Scientific Linux versus Ubuntu) and/or the version of NetCDF libraries have big impacts on values of model simulations? Or should we only expect numerical noises? Thanks!

**Comment by yantosca** [comment] 2021-03-29 20:49
Thanks @FeiYao-Edinburgh for writing.  Compiler versions and options can impact the outcome of simulations.  You have to take a look at which compiler options you are using.  Sometimes newer compiler versions deprecate old options, and this can potentially cause numerical differences (especially for options controlling math libraries or optimizations). 

I wouldn't think the netCDF library version would affect output.  But if I remember right, GCC/Gfortran relies on certain OS-dependent libraries (esp. for the math) whereas Intel Fortran ships with its own proprietary versions of those.

I would recommend asking your IT people about these numerical issues and tell them that you are trying to reproduce older results, and see what they recommend.

**Comment by FeiYao-Edinburgh** [comment] 2021-03-29 21:58
Thanks @yantosca for reply. Personally I use Intel compiler, so I believe that both netCDF version and OS should impact nothing? The only thing that I should keep in mind is the Intel compiler version and thereby options that may subject to change.

More specifically, we have two machine with the OS and Intel compiler info as below.
Old machine:
```
hardware: AMD EPYC 7662 64-Core Processor
OS: Scientific Linux 7.8 (Nitrogen)
compiler: ifort (IFORT) 16.0.0 20150815
```
New machine:
```
hardware: AMD EPYC 7542 32-Core Processor
OS: Ubuntu 20.04.2 LTS
compiler: ifort (IFORT) 2021.1.2 20201208
```
I tried compile the GEOS-Chem model on both machines. I found that for RRTMG simulations, the newer ifort on the new machine complained the option "-override-limits" that is not supported. Following the bug prompts, I changed one line of code in `./GeosRad/Makefile`, i.e. `OPT     := -O1 -override-limits` => `OPT     := -O1 -qoverride-limits`. This way I removed the compilation error and successfully compiled and run the GEOS-Chem model. Interestingly, I found that `OPT     := -O1 -qoverride-limits` also works for the older ifort on the old machine. May I kindly ask whether `-override-limits` versus `-qoverride-limits` are not math/optimization related? Switching between them won't impact numerical values? Are they invented for similar purpose, with the `-qoverride-limits` backward compatible with the `-override-limits`?

I know I can schedule two short runs to compare, but I suppose I may get a quicker answer from you. Thanks again for your help!

**Comment by lizziel** [comment] 2021-03-30 13:21
Hi @FeiYao-Edinburgh, the RRTMG Intel compilation bug is fixed in 12.9 but only if compiling with CMake. We retired use of GNU Make in version 13.0 but kept around the GNU Makefiles until that version to allow a transition period. However, we were not updating the Makefiles as extensively as the CMake files during the transition since they were slated for deletion.

If you haven't already I strongly suggest you build with CMake. This will be required when you upgrade to the next version. As for the case of RRTMG, it may also fix some compiler bugs you encounter using the old Makefiles.

**Comment by yantosca** [comment] 2021-03-30 13:40
Thanks for writing @FeiYao-Edinburgh.  A couple of other thoughts:

  1. Scientific Linux and Ubuntu are two very different Linux distros.  Most distros only share the Linux kernel and the GNU user functons (i.e. all the stuff like grep, ls, mkdir, vim, emacs, etc) but that's where the similarities end.  It is probably not reasonable to expect 100% bitwise identical results when comparing code that is run on different OS versions.  There will probably always be some numerical noise differences (i.e. diffs ~1e7 lower than values).
 
  2. Intel Fortran 2021 is probably *very* different than Intel 2016.  I know that the newer compilers often skew more heavily to the more modern Fortran standards.  Also they may use different optimizations that could affect results.
  
  3. I noticed you are using Intel-compiled code with AMD chips.  This in general leads to very poor performance. The Intel compiler will not use AMD-specific chip optimizations (this was a business decision about 20 years ago when Intel was trying to drive AMD out of the CPU market).  Long story short, you might get better performance with GNU Fortran on the AMD compiler for this reason.

**Comment by FeiYao-Edinburgh** [comment] 2021-03-30 19:02
Thanks @lizziel for reminding CMake in v13.0.0 that I will for sure use in the future. Currently I am using v12.9.3 which also compiles RRTMG correctly with the Intel compiler. I have checked that `-override-limits` and `-qoverride-limits` are for the same purpose (disable the internal limits and continue optimizing), with the latter introduced in newer versions, i.e. 15.0 and later,

Thanks @yantosca for providing thoughts on OS, Intel compiler versions, and inconsistency between Intel compiler and AMD chips. My another thought is that due to the inconsistency of compiler versions, the consistency between simulations from ifort and gfortran will for sure also be influenced by respective compiler versions. I now believe that I should keep using the same OS and compiler for a range of experiments for a fair comparison.

Thank you both for the discussion!

**Comment by FeiYao-Edinburgh** [comment] 2021-03-31 13:33
Hi @yantosca . Following your third hint, I tried compiling GCv12.9.3 on the new machine with `gfortran`. But I encountered a compilation bug as below. Which Makefile could I modify to overcome this bug?
```
rrtmg_lw_k_g.F90:4298:0:

 4298 |       subroutine lw_kgb03
      |
note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
```

**Comment by FeiYao-Edinburgh** [comment] 2021-04-15 09:00
Hi there, can you help me with the above compilation bug using `gfortran` with RRTMG simulation in v12.9.3?
