### ISSUE TITLE
[BUG/ISSUE] Restart files in Hg simulation

### ISSUE THREAD

**Issue by Dimakis8** [geoschem/geos-chem#957] opened 2021-10-15 07:09 UTC
Dear all,

I would like to make a question. I am using geos chem 13.0.2 for mercury simulation on 2x2.5 grid.

my mercury menu in input.geos is the following:
```
%%% MERCURY MENU %%% :
Error check tag/tot Hg? : F
Use dynamic ocean Hg? : F
Preindustrial sim? : F
Use GTMM soil model? : F
GTMM Hg rst file (bpch) : GTM.totHg.YYYYMMDDhh
Use Arctic river Hg? : T
Tie HgII(aq) red to UVB?: T.
```
The error reported is about the restart files and related with the snowpack hg source.
```
Restart.filename: './GEOSChem.Restart.%y4%m2%d2_%h2%n2z.nc4',
Restart.format: 'CFIO',
Restart.frequency: 00000100 000000
Restart.duration: 00000100 000000
Restart.mode: 'time-averaged'
Restart.fields: 'SpeciesRst_?ALL? ', 'GIGCchem',
'Met_DELPDRY ', 'GIGCchem',
'Met_PS1WET ', 'GIGCchem',
'Met_PS1DRY ', 'GIGCchem',
'Met_SPHU1 ', 'GIGCchem',
'Met_TMPU1 ', 'GIGCchem',
# 'Chem_OceanHg0 ', 'GIGCchem',
# 'Chem_OceanHg2 ', 'GIGCchem',
# 'Chem_OceanHgP ', 'GIGCchem',
# 'Chem_SnowHgOcean ', 'GIGCchem',
# 'Chem_SnowHgLand ', 'GIGCchem',
# 'Chem_SnowHgOceanStored ', 'GIGCchem',
# 'Chem_SnowHgLandStored ', 'GIGCchem',
```
When the restart fields are including ONLY the SpeciesRst_Hg0-Hg2-HgP and the MET fields, the simulation is running.

When I add the 'Chem_OceanHg0 ', 'Chem_OceanHg2 ','Chem_OceanHgP ', 'GIGCchem' 'Chem_SnowHgOcean ', 'Chem_SnowHgLand ',
'Chem_SnowHgOceanStored ', 'Chem_SnowHgLandStored ', I am getting the following error for each one of the snow/ocean variables:
```
HISTORY (INIT): Opening ./HISTORY.rc
===============================================================================
GEOS-Chem ERROR: CHEM_OCEANHG0 is not found in the registry for the CHEM object!
-> at Registry_Lookup (in Headers/registry_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Could not locate Chem_OceanHg0 chemistry state registry.
-> History_AddItemToCollection (in History/history_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Could not add diagnostic "Chem_OceanHg0" to collection: Restart
-> at History_ReadCollectionData (in module History/history_mod.F90)

-> ERROR occurred at (or near) line 70 of the HISTORY.rc file
===============================================================================
```
Is it a variable name bug, the way things are computed changed or I am doing something wrong??Is it sure that this, is not affecting the other mechanisms and the results?

Looking forward to your reply,

Thank you very much!

**Comment by yantosca** [comment] 2021-11-02 20:17
I was able to reproduce this issue.  It seems that the various State_Chm%OceanHg0 etc. fields have not been registered for the diagnostics.  This was probably an oversight or was lost in the shuffle as we modernized the code.  I can work on a solution.

**Comment by yantosca** [comment] 2021-11-02 20:24
Actually upon further review, these fields should be getting registered in this code in state_chm_mod.F90 (at least it is in v13):

https://github.com/geoschem/geos-chem/blob/ba58da4a6e447e47714fe5e7da488d15432a6fdc/Headers/state_chm_mod.F90#L2378-L2648

I can look into why this isn't working further.

**Comment by yantosca** [comment] 2021-11-02 21:04
It looks like there is an issue in the wildcarding of the species
```console
 CHEM_SNOWHGLANDSTORED_         | Non-reducible Hg sno | xy    | kg
 CHEM_SNOWHGOCEANSTORED_        | Non-reducible Hg sno | xy    | kg
 CHEM_SNOWHGLAND_               | Reducible Hg snowpac | xy    | kg
 CHEM_SNOWHGOCEAN_              | Reducible Hg snowpac | xy    | kg
 CHEM_OCEANHGP_                 | HgP ocean mass       | xy    | kg
 CHEM_OCEANHG2_                 | Hg(II) ocean mass    | xy    | kg
 CHEM_OCEANHG0_                 | Hg(0) ocean mass     | xy    | kg
```

**Comment by yantosca** [comment] 2021-11-03 15:39
This issue should now be fixed with commit 51fa209141a075c0b39c2ef0622137e9ae11e886.  The issue was that we were trying to add a second underscore into the diagnostic name, but the second but this is not necessary.  I will merge this into 13.3.1.

NOTE: The tagged Hg simulation now appears to be broken but we look to the community to fix this.

**Comment by yantosca** [comment] 2021-11-03 20:49
PR #986 has now been merged into the 13.3.1 development stream, so we can close this issue.

**Closed by yantosca** 2021-11-03 20:49 UTC
Labels: bug

**Comment by CharikleiaGRN** [comment] 2021-11-16 10:10
Ciao again!

I made the modifications in 13.0.2 code and it now reads and feeds the snowpack and ocean variables. However, I used a produced restart file to set up a new simulation and I am getting another error for the restart file. I am wondering whether I am missing another related bug fix or we still have work to do for Hg simulation or I am doing something wrong.

[restartfiles.txt](https://github.com/geoschem/geos-chem/files/7545305/restartfiles.txt)
[HEMCO.log](https://github.com/geoschem/geos-chem/files/7545252/HEMCO.log)

Thank you!!!!!

**Comment by yantosca** [comment] 2021-11-16 15:06
@CharikleiaGRN, try changing the time cycle flag for the SPC_RST entry in your HEMCO_Config.rc file to CYS.  In GEOS-Chem 13 we added some checks to make sure that the run will stop if the restart file time does not match the simulation time.  See issue #971.

**Comment by CharikleiaGRN** [comment] 2021-11-16 15:17
I will check it out now. thanks for the answer.
