### ISSUE TITLE
Error in computing F_OF_PBL

### ISSUE THREAD

**Issue by cugxiongjiajun** [geoschem/geos-chem#2219] opened 2024-03-27 01:50 UTC
### Name and Institution (Required)

Name:jjxiong
Institution:CUG

### Confirm you have reviewed the following documentation

- [√ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ √] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [√ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [√ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Hello,When I tried to start the simulation on 2013-06-15,I encountered the following error(simulation time:2013-06-15 to 2013-08-01),Before this, I used the restart file on the official website to simulation time:2013-07-01 to 2013-08-01 everything worked fine. I pass ncatted -a units, time, o ,c, "hours since the 2013-06-15 00:00:00" GEOSChem. Restart. 20130801 _0000z nc4 got the 2013-06-15 Restart file.

```
Species 220,     XYLE: Min = 0.000000000E+00  Max = 9.073718443E-10
GET_BOUNDARY_CONDITIONS: Done applying BCs at 2013/06/15 00:00
 bad sum at:            1          27
 bad sum at:            4          89
 bad sum at:            4          13
 bad sum at:            4          47
 bad sum at:            4          21
 bad sum at:            4          25
 bad sum at:            1          77
 bad sum at:           27          99
 bad sum at:            4          22
 bad sum at:            4          14
 bad sum at:            2          77
 bad sum at:            4          27
 bad sum at:            4          15
 bad sum at:            4          23
 bad sum at:            3          77
 bad sum at:           28          99
 bad sum at:            4          33
 bad sum at:            4          77
 bad sum at:           29          99
 bad sum at:            4          26
 bad sum at:            4          90
 bad sum at:            4          24
 bad sum at:            1          29
 bad sum at:            4          31
 bad sum at:            4          29
 bad sum at:            1          28
 bad sum at:            4          28
 bad sum at:            4          16
 bad sum at:            1          30
 bad sum at:            4          30
 bad sum at:            4          32
 bad sum at:            4          19
 bad sum at:            4          17
 bad sum at:           26          97
 bad sum at:            3          78
 bad sum at:            4          34
 bad sum at:            4          91
 bad sum at:            4          78
 bad sum at:            4          20
 bad sum at:            4          48
 bad sum at:           27          97
 bad sum at:            4          18
 bad sum at:           28          97
 bad sum at:           29          97
 bad sum at:           30          97
 bad sum at:           31          97
 bad sum at:           32          97
 bad sum at:           33          97
 bad sum at:           34          97
 bad sum at:           35          97
 bad sum at:            4          93
 bad sum at:           47           1
 bad sum at:           58           1
 bad sum at:           26          98
 bad sum at:           27          98
 bad sum at:           28          98
 bad sum at:           29          98
 bad sum at:           30          98
 bad sum at:           31          98
 bad sum at:           32          98
 bad sum at:           33          98
 bad sum at:            4          95
 bad sum at:            4          96
 bad sum at:            4          92
 bad sum at:            4          79
 bad sum at:            4          87
 bad sum at:            4          94
 bad sum at:            4          88
 bad sum at:           47           2
 bad sum at:           47           3
 bad sum at:           56           3
 bad sum at:           47           4
 bad sum at:            4          35
 bad sum at:           56           4
 bad sum at:            1          75
 bad sum at:            2          75
 bad sum at:            4          75
 bad sum at:            4          49
 bad sum at:            1          76
 bad sum at:            2          76
 bad sum at:            3          76
 bad sum at:            4          76
 bad sum at:            4           5
 bad sum at:            4           6
 bad sum at:            4           7
 bad sum at:            4          10
 bad sum at:            4           8
 bad sum at:            4          11
 bad sum at:            4           9
 bad sum at:            4          12
 bad sum at:            4          37
 bad sum at:            4          39
 bad sum at:            4          36
 bad sum at:            4          80
 bad sum at:            4          38
 bad sum at:            4          81
 bad sum at:            4          40
 bad sum at:            4          82
 bad sum at:            4          83
 bad sum at:            4          84
 bad sum at:            4          41
 bad sum at:            4          85
 bad sum at:            4          86
 bad sum at:            4          50
 bad sum at:            4          42
 bad sum at:            4          45
 bad sum at:            4          43
 bad sum at:            4          46
 bad sum at:            4          44
 bad sum at:            4          51
 bad sum at:            4          52
 bad sum at:            4          53
 bad sum at:            1          73
 bad sum at:            2          73
 bad sum at:            4          73
 bad sum at:            1          74
 bad sum at:            4          74
 bad sum at:            4          54
 bad sum at:            4          55
 bad sum at:            1          71
 bad sum at:            2          71
 bad sum at:            3          71
 bad sum at:            4          71
 bad sum at:            1          72
 bad sum at:            2          72
 bad sum at:            3          72
 bad sum at:            4          72
 bad sum at:            4          69
 bad sum at:            4          57
 bad sum at:            1          70
 bad sum at:            2          70
 bad sum at:            4          70
 bad sum at:            4          58
 bad sum at:            4          59
 bad sum at:            4          56
 bad sum at:            4          67
 bad sum at:            1          65
 bad sum at:            1          63
 bad sum at:            2          61
 bad sum at:            4          63
 bad sum at:            4          68
 bad sum at:            2          65
 bad sum at:            4          60
 bad sum at:            4          61
 bad sum at:            3          65
 bad sum at:            4          65
 bad sum at:            1          64
 bad sum at:            2          64
 bad sum at:            4          64
 bad sum at:            1          62
 bad sum at:            2          62
 bad sum at:            3          62
 bad sum at:            4          66
 bad sum at:            4          62
===============================================================================
GEOS-Chem ERROR: Error in computing F_OF_PBL !
COMPUTE_PBL_HEIGHT ("pbl_mix_mod.F90")
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "COMPUTE_PBL_HEIGHT" at initialization!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)

```
Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

HEMCO.log:

```
HEMCO WARNING: Data is treated as unitless, but file attribute suggests it is not: mol mol-1 dry. File: /data/jjxiong/GEOS-B02/OutputDir/GEOSChem.BoundaryConditions.20130615_0000z.nc4
--> LOCATION: HCOIO_READ (HCOIO_READ_STD_MOD.F90)
```

version:
GCClassic-13.4.1
HEMCO-3.4.0

**Comment by lizziel** [comment] 2024-03-27 15:20
I edited the original issue for readability.

**Comment by yantosca** [comment] 2024-03-29 21:15
Thanks for writing @cugxiongjiajun.  I think this issue might be caused by corrupted boundary conditions, since the message 
```console
GET_BOUNDARY_CONDITIONS: Done applying BCs at 2013/06/15 00:00
```
precedes all of the `bad sum` errors.  I would make sure you do not have any negative or NaN values in that particular boundary conditions file.

**Comment by cugxiongjiajun** [comment] 2024-04-01 08:16
Thanks for your  answer @yantosca , I used the same boundary condition and then advanced the start date from 2013/06/15 to 2013/06/02 (the restarts file was modified from 2013/06/01) and it works fine.

**Comment by cugxiongjiajun** [comment] 2024-04-01 08:18
In this case, could it be a problem with Boundary conditions?

**Comment by yantosca** [comment] 2024-06-05 20:36
Closing out this issue.

**Closed by yantosca** 2024-06-05 20:36 UTC
Labels: category: Bug, topic: Runtime Error
