### ISSUE TITLE
GEOSChem restart file not found for year of interest

### ISSUE THREAD

**Issue by msulprizio** [geoschem/geos-chem#1503] opened 2022-11-14 15:08 UTC
### Discussed in https://github.com/geoschem/geos-chem/discussions/1499

<div type='discussions-op-text'>

<sup>Originally posted by **erinemme** November 11, 2022</sup>
Hello, 
I am trying to run GEOS-Chem and ran into an error regarding my restart file (screenshot also attached):
HEMCO ERROR: Cannot find file for current simulation time: ./GEOSChem.Restart.20011101_0000z.nc4 - Cannot get field SCP_ACET. Please check file name and time (incl. time range flag) in the config. file
![gcrestart_error](https://user-images.githubusercontent.com/90405034/201407105-751fdbfa-0557-4532-ac1e-409b371b6432.png)
This error was shown in HEMCO.log. It does not seem that there are any GEOS-Chem restart files available for download for year 2001. Additionally, I tried to do a dry run (with 6month spin up) to create the correct restart files, and this didn't seem to work either. It also seems that it is looking for the GEOS-Chem restart file and cannot find it (the month here is different as this was a part of me trying to run the spinup):
HEMCO: OPTIONAL FILE NOT FOUND ./HEMCO_restart.200107010000.nc
HEMCO: REQUIRED FILE NOT FOUND ./GEOSChem.Restart.20010701_0000z.nc4
This error was shown in the dry run log. I do have a GEOS-Chem restart file within my run directory, but it is for a different year (it was automatically downloaded after creating my run directory). I have looked all over the GEOS-Chem wiki and github and couldn't find anything that has solved this problem yet. 

Thank you in advance for the help. </div>

**Comment by yantosca** [comment] 2022-11-14 15:11
This is a duplicate of #1450.  Please see that issue for a solution.

**Comment by yantosca** [comment] 2022-11-14 15:11
Also tagging @Jourdan-He and @SaptSinha

**Comment by erinemme** [comment] 2022-11-14 15:17
@yantosca thank you so much for pointing out this is a duplicate question. I spent quite a bit of time searching the github for an answer but must have missed this question before. I think it is unclear in the GEOS-Chem readthedocs what to do if your restart file is not within the time frame of 2010-2019. It would be very helpful if this was updated for future use. Thank you again!

**Comment by yantosca** [comment] 2022-11-14 15:27
Thank you @erinemme for the suggestion.  We'll see if we can make that clearer in the ReadTheDocs for the next version.

**Comment by yantosca** [comment] 2022-11-14 17:36
@erinemme: I've pushed an update to our `docs/dev` branch, which you can view in the ReadTheDocs ["latest" version](https://geos-chem.readthedocs.io/en/latest/gcc-guide/04-data/restart-files-gc.html#how-are-restart-files-read-into-geos-chem).  I hope this is more clear now.

The default ReadTheDocs always points to the "stable" version (i.e. the last Github release, which is 14.0.1).  The "latest" version is for any documentation updates on our development branches.

**Comment by yantosca** [comment] 2022-11-14 18:19
Thanks @erinemme!  That documentation will ship with GEOS-Chem 14.0.2, our next patch version, but for now it's in "latest".  I'll close out this issue now.

**Closed by yantosca** 2022-11-14 18:19 UTC
Labels: documentation, duplicate, runtime
