### ISSUE TITLE
[BUG/ISSUE] Using 3-hourly boundary conditions for the GEOS-Chem nested simulation

### ISSUE THREAD

**Issue by katiegrace-3000** [geoschem/geos-chem#248] opened 2020-03-18 03:19 UTC
My issue is similar like the previous issue while the solution doesn't help my case. 
https://github.com/geoschem/geos-chem/issues/226

I am using V12.7.1, and I know another user using V12.7.0 also has same issue. 

The GEOS-Chem nested simulation could go through only if I have hourly boundary condition from the global run. If I use every 3 hour boundary condition, the nested simulation will say can't find the right time stamp. 

Thanks.

**Comment by yantosca** [comment] 2020-03-18 13:56
We would recommend to update to 12.7.2 if possible.  12.7.2. should have the fix applied in commit: https://github.com/geoschem/geos-chem/commit/722a151c9748bc117b6fcfcb910892f3858836be.

**Comment by yantosca** [comment] 2020-03-25 13:53
I am closing out this issue. Feel free to reopen.

**Comment by katiegrace-3000** [comment] 2020-04-13 21:42
> We would recommend to update to 12.7.2 if possible. 12.7.2. should have the fix applied in commit: [722a151](https://github.com/geoschem/geos-chem/commit/722a151c9748bc117b6fcfcb910892f3858836be).

I did tests of 12.7.2, however, the same issue remained. It takes so much disk space. :) Thanks a lot.

**Comment by katiegrace-3000** [comment] 2020-04-14 03:52
Hi, Bob,

I tested the new version of GEOS-Chem for the nested run. While still same story. I only could use global output of boundary condition as 1 hour frequency. So I tested 12.7.0, 12.7.1, and 17.7.2, they are all same about this issue. It takes a lot of space when I am doing a couple of years simulation. :) Much appreciated. Sorry I haven't figured out how to re-open an old post yet. :)

Best.

Cui
________________________________

**Comment by msulprizio** [comment] 2020-04-14 13:27
Can you provide us with the following files from your 12.7.2 runs so we can better diagnose the issue. You should be able to attach them to this issue (you may just need to change the file extension to .txt).

From your global simulation used to save out the boundary conditions:
1. `HISTORY.rc` (contains settings to save out BCs)
2. GEOS-Chem log file

From your nested grid simulation:
1. `HEMCO_Config.rc` (contains settings to read in BCs)
2. `lastbuild*` (contains information about the state of the code used in your run)
3. GEOS-Chem log file

**Comment by jennyfisher** [comment] 2020-05-01 07:16
Hi folks. I am having a similar problem, also using 12.7.2. Originally the error message was:
`HEMCO ERROR: Cannot find field with valid time stamp in BCs/GEOSChem.BoundaryConditions.20160101_0000z.nc4 - Cannot get field BC_Rn222. Ple
ase check file name and time (incl. time range flag) in the config. file`

After checking the log for issue #226 I noticed that there was a mention in that issue with running on the first day for which there were boundary conditions files (e.g. when they had BCs starting at Oct 6, they could only run if they started the nested simulation at Oct 7).

So I tried starting my simulation on the second day for which I have BCs but it hit the same error (just with slightly different time stamps).

Also, a quick note that the wiki documentation hasn't been updated to reflect the fix in Issue #226 to change 0-23 to *: http://wiki.seas.harvard.edu/geos-chem/index.php/Setting_up_GEOS-Chem_nested_grid_simulations#Set_up_your_nested_grid_run_directory

(But that hasn't helped me anyhow!).

I'm attaching a zip file with:
- HEMCO_Config.rc
- HEMCO.log.day1 -- log from my original run for the first day with BCs
- HEMCO.log.day2 -- log from my second run for the second day with BCs
- log.geos_debug
- ncdump_out.txt -- output from the command `ncdump -v time GEOSChem.BoundaryConditions.20160102_0000z.nc4`

Here is the relevant information from lastbuild:
`  LAST_COMMIT  : Use Ordonez files with shifted latitude to fix run error at c360
  COMMIT_DATE  : Fri Feb 28 15:19:33 2020 -0500
  VERSION      : 12.7.2
  VERSION_TAG  : GC_12.7.2
`
I haven't tried Cui's solution of using hourly BCs.

Thanks,
Jenny

[Archive.zip](https://github.com/geoschem/geos-chem/files/4562839/Archive.zip)

**Comment by jennyfisher** [comment] 2020-05-07 03:01
Hi @msulprizio @yantosca --

Just some further follow-up. I have done a couple of tests and found the nested simulation runs successfully if:
1. I use hourly BCs
2. I start the simulation on the 2nd day for which I have BCs.

It does not work with 3-hourly BCs (any start date). It also doesn't not work with hourly BCs if I start on the first day for which I have BCs.

Note that my files are all the same as in the previous post, I just tested with new BC files saved from the full simulation and with different start dates.

Cheers,
Jenny

**Comment by katiegrace-3000** [comment] 2020-05-07 03:04
Yes, I could understand it doesn’t work for the firs day because the first day’s time stamp starts from 3:00, so 0:00 is not found.
I really wish it could work for every 3 hours boundary condition, it will save a lot disk space. Thanks.

**Comment by jennyfisher** [comment] 2020-05-07 03:07
Me too! I'm hoping GCST can help us out! I didn't realise about the first day's timestamp - it would be useful if that info was in the wiki page describing how to use FlexGrid.

Cheers,
Jenny

**Comment by msulprizio** [comment] 2020-05-07 13:33
Yes, when generating boundary condition files, it is recommended that you generate them for at least one day before the start date of your nested-grid simulation to ensure you have hour 0 in the boundary condition file for the first day. We can add this information to the wiki.

I am looking into the issues reported above now. For what it's worth, the nested grid simulations are working in 12.8.0 as verified by [the unit test for that version](http://ftp.as.harvard.edu/gcgrid/geos-chem/1mo_benchmarks/GC_12/12.8.0/GCC/Plots/GC_12.8.0_Mar30.results.html). Those unit tests are only run for one chemistry timestep though, so we may need to run for longer to run into the issues reported here.

**Comment by msulprizio** [comment] 2020-05-15 13:44
Hi all. I tried to reproduce the error by running a 4x5 simulation for 2016/06/30-2016/07/02 and saving out 3-hourly BCs to daily files. I then submitted a nested NA run for  2016/07/01 and did not encounter this error. It then occurred to me that this may be related to issue https://github.com/geoschem/geos-chem/issues/269. In my test, my 4x5 run was continuous over the start date of the nested NA run, so hours 0-21 of 2016/07/01 was included in the BC file. However, if you're running in monthly segments, for example, the BC for 2016/07/01 00:00 will be written out at the end of your 4x5 June run. Once the 4x5 July run begins, the file dated 20160701 will be overwritten and the resulting BC file will only include hours 3-21. 

@yantosca implemented a fix in the `dev/12.8.1` branch so that the output for hour 0 on 20160701 will not be overwritten, but instead saved to a different file. This means that between the two monthly 4x5 runs, there would be two BC files for that day -- `GEOSChem.BoundaryConditions.20160701_0000z.nc4` with hour 0 and `GEOSChem.BoundaryConditions.20160701_0300z.nc4` with hours 3-21. The two files will need to be merged with `cdo mergetime` before starting the nested run so that all of the BCs for one day can be found in a single file.

**Comment by katiegrace-3000** [comment] 2020-05-15 14:37
Good morning. Thanks a lot for working on this. I’ve been paying attention with the start hour, I know it should start with 0 no matter we use every 1 hour or 3 hour global boundary data. For monthly segment issue, I usually restart from a day earlier in order to have 0 timestamp for the 2nd, and I copy the HEMCO_restart as one day before the real day. So even I always have the 0 timestamp, I have same issue, 1 hour frequency global boundary data works, but 3 hour frequency global boundary doesn’t work. I wondered should I change something on the following line to use every 3 hour global boundary?

(((GC_BCs
* BC_  $ROOT/SAMPLE_BCs/v2019-12/tropchem/GEOSChem.BoundaryConditions.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesBC_?ADV?  1980-2019/1-12/1-31/0-23 RFY xyz 1 * - 1 1
)))GC_BCs

Thanks a lot.

Cui

**Comment by msulprizio** [comment] 2020-05-15 18:49
Ah, I see it! You need to change the hour field from 0-23 to * so you have:

```
(((GC_BCs
* BC_  $ROOT/SAMPLE_BCs/v2019-12/tropchem/GEOSChem.BoundaryConditions.$YYYY$MM$DD_$HH$MNz.nc4 SpeciesBC_?ADV?  1980-2019/1-12/1-31/* RFY xyz 1 * - 1 1
)))GC_BCs
```

The `*` will tell HEMCO to read the BCs for the entire day at the beginning of the day. Then, the code within `GeosCore/hcoi_gc_main_mod.F90` will try to update the BC fields every three hours. Using 0-23 in the hour field tells HEMCO to update the field hourly, but it crashes when it's not hour 0, 3, 6, etc. because it can't find the BCs for that hour.

**Comment by jennyfisher** [comment] 2020-05-18 00:51
Thanks @msulprizio ! I am now fairly confident that the fix implemented by @yantosca in v12.8.1 will solve the existing problem for me (I already had the hour field set to *). I haven't pulled this fix, but I tried running my 4x5 simulation continuously from 2016070100 to 2016070300. At the end, I had BC files with 7 timestamps (3h-21h) for 20160701, 8 timestamps (0h-21h) for 20160702, and 1 timestamp (0h) for 20160703. I then ran my nested simulation from 2016070200 to 2016070300 and everything worked. I think the time before I had tried two consecutive 1-day runs to create the BCs, so they would have been overwriting the 0h BC as suggested.

There is still some weird lingering behaviour. I am trying to do some short test runs of my nested simulation, just a few hours, so I tried running for a few hours on 20160101 (the first day for which I have BCs). My BC file shows there are fields from 3h onwards. I've set my start time in input.geos to be 20160101 030000 or later (even starting as late as 120000) so that it wouldn't need the BC from 0h. However, it always crashes trying to find the BC and always seems to be looking for a "preferred datetime" at 0h, even though this is not the closest hour to the start time of the sim.

For example, in input.geos:
```
Start YYYYMMDD, hhmmss  : 20160101 120000
End   YYYYMMDD, hhmmss  : 20160101 150000
```

Output to HEMCO.log:
 ```
Opening file: BCs/GEOSChem.BoundaryConditions.20160101_0000z.nc4
HEMCO: Entering GET_TIMEIDX (hco_read_std_mod.F90) ( 6)
 Number of time slices found:            7     
 Time slice range :    201601010300.000        201601012100.000
          preferred datetime:  201601010000.
              selected tidx1:             -1    
        assigned delta t [h]:              0     
 local time?  F
HEMCO: Leaving GET_TIMEIDX (hco_read_std_mod.F90) ( 6)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Cannot find field with valid time stamp in BCs/GEOSChem.BoundaryConditions.20160101_0000z.nc4 - Cannot get field BC_Rn222. Please check file name and time (incl. time range flag) in the config. file
```

ncdump output of BC file (partial):
```
netcdf GEOSChem.BoundaryConditions.20160101_0000z {
dimensions:
	time = UNLIMITED ; // (7 currently)
	lev = 72 ;
	ilev = 73 ;
	lat = 26 ;
	lon = 23 ;
variables:
	double time(time) ;
		time:long_name = "Time" ;
		time:units = "minutes since 2016-01-01 00:00:00 UTC" ;
		time:calendar = "gregorian" ;
		time:axis = "T" ;
...
data:

 time = 180, 360, 540, 720, 900, 1080, 1260 ;
}
```

Thanks,
Jenny

**Comment by katiegrace-3000** [comment] 2020-05-18 00:57
I recalled something, the global 3 hours boundary condition actually worked for me very well for the first 23 hours, then it crashes. This situation happened to both 12.7.1 and 12.8.1. I heard others also have this issue, it only worked for the first 23 hours. Thanks for all your efforts and I think it’s getting there. 😊

**Comment by tianjialiu** [comment] 2020-06-29 20:51
I've had a similar issue with running a nested grid simulation (version 12.8.2), where it crashes after the first day. HEMCO.log indicates a "Wrong dimensions" error when reading the BC file on day 2. When reading the BC file on day 2, the BC file has one time slice.

A tentative solution (by @jimmielin) is to run the global 4x5 (or 2x2.5) simulation used for the spin-up across the spin-up period and the nested grid simulation period and output 3-hourly BC files every day. So if I want to run a 2014-2019 nested grid simulation, I would first need to run a global 4x5 simulation from 2013-2019 (1-yr spin-up). I tested this for a few days, and the nested grid simulation was successful. When doing the nested grid simulation, BCs need to be turned off in HISTORY.rc or else GC will overwrite the 4x5 BC file on day 2.

- Tina

**Comment by yantosca** [comment] 2020-06-29 21:18
@tianjialiu: This behavior probably related to this issue: https://github.com/geoschem/geos-chem/issues/269, for which a fix (commit https://github.com/geoschem/geos-chem/commit/94d78a7d3bc1ac205f0fc7b682c65d98e3f4bbe2) was introduced in 12.8.1.  

The new behavior is that a file with timestamp 0000z will be written on at the end of a simulation.  If you start a subsequent run stage, the new files will be written out at time 0100z.  Therefore you may need to concatenate files together so that your boundary conditions always have 24 time slices.

**Comment by jimmielin** [comment] 2020-06-29 21:21
Hi all, I'd also like to add to the information that it is crucial that all files read by HEMCO in the same collection have the same time number of time slices. This is because HEMCO asserts the array once at the beginning of the read and does not dynamically re-allocate according to further files, so all netCDF files in one collection must have a consistent temporal spacing and # of time slices.

There also seems to be some confusion surrounding the provisioning of boundary condition files. Would it be possible for GCST to offer some official guidance on the new GEOS-Chem boundary conditions wiki page to clarify that:
1. Boundary conditions from a global run must be available throughout the **entire** nested-grid simulation run time
2. The recommended temporal resolution for the boundary conditions, and
3. Disable `HISTORY.rc` output of `BoundaryConditions` in the **nested** run to prevent overwrites (a common mistake we've seen in this thread?)

Thanks!

**Comment by neyranaz** [comment] 2020-08-25 18:57
This issue appears to be relevant when generating the Boundary Conditions in segments. Specifically, in preparation for our Aerosol Only Nested Grid run (2014-2019), we produced boundary conditions in annual segments (P.ex 20140101-20150101). We then used the 2nd day (20140102) suggestion that Jenny proposed in this thread, to start our nested grid run, and GC successfully produced the results for the first segment of our Nested Grid run, however, as we went on to produce the second segment (20150101-20160101), we obtained the time stamp error. 

```
--> LOCATION: HCOIO_READ_STD (hcoio_read_std_mod.F90)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
HEMCO ERROR: Cannot find field with valid time stamp in ./BC_4x5/GEOSChem.BoundaryConditions.20150102_0000z.nc4 - Cannot get field BC_DMS. Please check file name and time (incl. time range flag) in the config. file
```

We then tested to see if this error disappeared if we initialized, the second day on the second segment (20150102-20160101), and we were able to initialize. But despite we can initialize on the second day of the second segment, it seems we shouldn't do so, as we would be losing one day of species concentrations. So it seems it might be very important to produce the Boundary Conditions altogether in the same run, rather than producing them in segments. 

`ncdump -h` of the file where the error occurred in `HEMCO.log ` 

	```
	:simulation_start_date_and_time = "2015-01-01 00:00:00z" ;
		:simulation_end_date_and_time = "2016-01-01 00:00:00z" ;
```

Has anyone else had a similar issue?

Thanks, 

Oscar

**Comment by msulprizio** [comment] 2020-09-01 15:24
Yes, to avoid issues you could generate BCs with a continuous simulation for your time period of interest. If you break your global simulation into segments, then you will need to combine BC files prior to your nested run. 

If running with GEOS-Chem 12.8.1 or later a fix (https://github.com/geoschem/geos-chem/issues/269) will be included to save BCs for hour 0 on the end date of your first segmented run to one file (ending in `_000z.nc4`), and hours 1-23 of that date to another BC file (ending in `_0100.nc4`) when you start the next segmented run. 

If using GEOS-Chem 12.8.0 or earlier, the BCs for hour 0 on the end date of your first segmented run will be saved to a file ending in `_0000z.nc4`. The next segmented run will overwrite that file to save hours 1-23 for the same date, so it is important to rename the file saved out at the end of your first run before submitting the next run. You can do this manually or in your run script.

Once both segmented runs are done, you can then combine the BC files for the end date of run 1 (containing hour 0) and start date of run 2 (containing hours 1-23) using a tool like `cdo mergetime`. You will want to name that file using the same format as the other days (i.e. ending in `_0000z.nc4`), so that the nested grid simulation can find this new file containing all hours (0-23) for that day.

**Comment by yantosca** [comment] 2020-12-18 23:16
I will close out this issue for now.  Please let us know if you are still having problems.

**Closed by yantosca** 2020-12-18 23:16 UTC
Labels: bug
