### ISSUE TITLE
what's the problem

### ISSUE THREAD

**Issue by rongbing0353** [geoschem/geos-chem#2577] opened 2024-11-19 23:17 UTC
### Your name

runbin

### Your affiliation

lanzhou university

### What happened? What did you expect to happen?

why is the problem

### What are the steps to reproduce the bug?

run the download_data.py
![problem](https://github.com/user-attachments/assets/5047fb77-1e3a-40ea-8131-dbb123db72b2)

### What GEOS-Chem version were you using?

13.0.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc10.2

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

0.5*0.625

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment] 2024-11-20 18:55
This is a duplicate of #2576.  Closing.

**Closed by yantosca** 2024-11-20 18:55 UTC
Labels: category: Bug, duplicate
