### ISSUE TITLE
How to add PM10 in GEOSChem 13.3.0

### ISSUE THREAD

**Issue by ycyeongi** [geoschem/geos-chem#2285] opened 2024-05-09 02:06 UTC
### Name and Institution (Required)

Name: chaeyeong
Institution: PNU

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

Please provide as much detail as possible. Always include the GEOS-Chem version number and any relevant configuration and log files.

I read 'https://github.com/geoschem/geos-chem/pull/992', changed aerosol_mod.F90 and state_diag_mod.F90 and HISTORY.rc and ran the model, but I keep getting the error below.
[aerosol_mod.zip](https://github.com/geoschem/geos-chem/files/15256681/aerosol_mod.zip)

![image](https://github.com/geoschem/geos-chem/assets/169321162/9ddfeb9a-1c3e-47dd-839b-351821629caf)

Is there something else I need to change?

**Comment by yantosca** [comment] 2024-05-09 17:10
Thanks for writing @ycyeongi.  What I would recommend is to check out the 13.4.0 code to and search for `PM10` in `Headers/state_diag_mod.F90`, and to compare that with your code.  Without knowing more it is hard to say what the issue is, but it looks like the PM10 diagnostic was not added to the registry object in `State_Diag`.

```console
git clone https://github.com/geoschem/GCClassic
git checkout -b 13.4.0
git submodule update --init--recursive
cd GCClassic/src/GEOS-Chem
grep -i PM10 */*.F*
```

**Comment by ycyeongi** [comment] 2024-05-13 07:28
Oh, I found my fault.. I didn't realize I had to change those files and **compile anew**. After changing the files and compiling, it works fine. Thanks for your help :)

**Comment by yantosca** [comment] 2024-05-13 18:46
Thanks for the update @ycyeongi!  We can close this issue out now.

**Closed by yantosca** 2024-05-13 18:46 UTC
Labels: category: Bug, topic: Diagnostics, topic: Aerosols
