### ISSUE TITLE
NOx chemical loss rate output from fullchem simulation

### ISSUE THREAD

**Issue by Kexin828** [geoschem/geos-chem#2257] opened 2024-04-22 07:25 UTC
### Name and Institution (Required)

Name: Kexin Zhang
Institution: Tsinghua University

### Confirm you have reviewed the following documentation

- [ ] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [ ] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [ ] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [ ] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I am using v 14.2.1

I would like to output the loss rates of NO and NO2, however this is not an option within the ProdLoss collection. 
I created KPP families for NO and NO2 loss in the file: fullchem.kpp, and then rebuild the KPP solver code, then recompile and rerun GEOS-Chem s the answer to question 1973（https://github.com/geoschem/geos-chem/issues/1973#issuecomment-1737704845).

But I encountered the following error during the run process. Could you please tell me how to proceed correctly? 
Thank you very much.
![image](https://github.com/geoschem/geos-chem/assets/149068356/0b5187a5-2594-48a2-9971-8fc79f94320d)

**Comment by yantosca** [comment] 2024-04-22 15:06
Thanks for writing @Kexin828.  The issue is that you need to specify a minimum set of metadata in the species database for all KPP family species.   Try adding these to `species_database.yml`:

```yaml
LNO:
  FullName: Dummy species to track loss of NO
  Is_Gas: true
  MW_g: 30.01
LNO2:
  FullName: Dummy species to track loss of NO2
  Is_Gas: true
  MW_g: 46.01
```
and then re-run.

**Comment by Kexin828** [comment] 2024-04-24 03:01
Thank you very much for your response, but after making the modifications to species_database.yml, I encountered a new error when trying to run it again. What should I do to handle it?
![image](https://github.com/geoschem/geos-chem/assets/149068356/9bbcfcc9-6701-49e1-9581-f505972aba45)

**Comment by yantosca** [comment] 2024-05-01 13:14
Thanks @Kexin828.  Did you rebuild the KPP mechanism with your updated family definition?  That might be the problem.

**Comment by yantosca** [comment] 2024-06-05 19:44
Closing out this issue

**Closed by yantosca** 2024-06-05 19:44 UTC
Labels: category: Bug, topic: Chemical Mechanisms, topic: Runtime Error, category: Debug Help
