### ISSUE TITLE
KPP integration failures with 14.2.0

### ISSUE THREAD

**Issue by sdeastham** [geoschem/geos-chem#1982] opened 2023-10-08 18:04 UTC
### Name and Institution (Required)

Name: Sebastian Eastham
Institution: MIT

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://gchp.readthedocs.io/en/latest/reference/SUPPORT.html)
- [x] [User manuals](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://gchp.readthedocs.io/en/latest/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/GCHP/issues)

### Description of your issue or question

Since transitioning to GCHP 14.2.0, I have found that the simulation fails frequently with KPP integrator errors. I suspect that this is due to ongoing problems with halogen chemistry which become especially visible at high resolution, as this seems to happen more often with simulations at C90 and C180. Attached is the log from a simulation for 2004, using the 14.0.0 C90 restart. The only other difference was that anthropogenic emissions from CEDS were forced to match those of year 2015 and non-standard aviation emissions were used. Prior simulations suggest that these two factors are unrelated although I am continuing to investigate. This error has been found to occur when using both the code from commit 2c5417bb0b3b351e2298d07e885685c7e0298c47 and from commit e4530fa662a671674ff8a00ce27bf718279d3f3e. Alarmingly, several species concentrations in the KPP error output are indicated as being negative.

[gchp.20040701_0000z.log](https://github.com/geoschem/GCHP/files/12841372/gchp.20040701_0000z.log)

**Comment by lizziel** [comment] 2023-10-10 15:11
Tagging @christophkeller since would impact GEOS runs with 14.2.0.

**Comment by yantosca** [comment] 2023-10-10 17:28
Tagging @msl3v (which is the correct handle for Mike)

**Comment by yantosca** [comment] 2023-10-16 17:45
@sdeastham: Have you looked to see if either the KaqHMS2 term or the FC term is going negative at that high resolution?

**Comment by sdeastham** [comment] 2023-10-16 19:02
@yantosca - I don't think either did. I'd guess that, if either was going negative, it would have been KaqHMS2 as FC is used in other reactions. However K_CLD(6) was positive. I suspect that the problem is instead that the calculation of K_CLD(6) assumes that SO2 will never become limiting - but here the concentration of SO2 was low, which means that the integrator ended up generating negative SO2 after which everything unraveled. I know though that @msl3v is looking into this. For the moment I've implemented an alternative formulation where the reaction is instead defined as `HMS + OH + SO2 --> 2PSO4 + 2SO4 + C2HO` and K_CLD(6) is divided by the concentration of SO2. It's a kludge - and Mike has very justified concerns about it - but the integrator doesn't seem to fall over any more and (for my specific purposes) that's my biggest concern.

**Comment by msl3v** [comment] 2023-10-17 20:45
Hey @sdeastham and @yantosca 

Seb, a boxmodel initialized with what you gave me reproduces the large negative values. And it is clear that having HMS >> SO2 causes the negative result. At least, setting SO2 ~= HMS in the initial conditions yields all positive results.

Some rethinking needs to be done to get the Moch HMS reactions integrated differently into the mechanism. It is difficult to allow SO2 to be consumed but not include it in the rate calculation, as is required by the formulation. While I do like being able to assign negative products to reactions, clearly there are limitations.

@sdeastham how does your fix seem to do with the rest of the atmosphere? Can you discern a major impact on sulfur species?

**Comment by yantosca** [comment] 2023-10-17 20:55
Thanks @sdeastham and @msl3v for looking into this.  Looking forward to your recommendations.

**Comment by sdeastham** [comment] 2023-10-18 18:11
Thanks indeed @msl3v for digging into this! So far, my kludge is not resulting in integration errors but I'm not certain that it's the ideal solution. If there are specific quantities I should look for in the output to make sure I'm not getting anything crazy that would be helpful to know; at the moment what I'm doing really is rather crude. I can imagine a host of different solutions but all of them fundamentally rely on something like a division by [SO2] or a clunky transition between two reactions when we approach the situation of [HMS] > [SO2]. Unfortunately I think the best solution will require a deep dive into how the Moch HMS reactions work, and how they're collapsed.

**Comment by msulprizio** [comment] 2023-12-05 19:02
The interim fix for this issue has been merged into the 14.3.0 development branch. I will close out this issue for now.

**Closed by msulprizio** 2023-12-05 19:02 UTC
Labels: bug, GCHP, KPP / chem mechanisms, Chemistry WG
