### ISSUE TITLE
In NcGet_Var_Attr_C: time, NetCDF: Variable not found

### ISSUE THREAD

**Issue by Naaimaben** [geoschem/geos-chem#2417] opened 2024-08-07 16:52 UTC
<img width="514" alt="geos-error" src="https://github.com/user-attachments/assets/7380e422-a93a-44a6-8b94-a1f5238a9fc8">

### What are the steps to reproduce the bug?

After running a simulation using **_./gcclassic_**

### Please attach any relevant configuration and log files.
```console
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.CH4.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.CO.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.Cl.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.Cl2.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.Cl2O2.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.ClO.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.EOH.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.ETP.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.GLYC.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.GLYX.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.H2402.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.H2O.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.H2O2.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.HAC.geos5.2x25.nc
HEMCO: Opening /home/naaima.benkadour/lustre/aq_model-z5xz2cq4sae/shared/ExtData//HEMCO/GMI/v2015-02/gmi.clim.HCFC141b.geos5.2x25.nc
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
In NcGet_Var_Attr_C: time, NetCDF: Variable not found
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 
This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
### What GEOS-Chem version were you using?

14.4.2

### What environment were you running GEOS-Chem on?

Other (please explain below)

### What compiler and version were you using?

Supercomputer 

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

GEOS-FP

**Comment by yantosca** [comment] 2024-08-12 17:46
Thanks for the update @Naaimaben.  What you can do is to turn on `Verbose: true` in the `HEMCO_Config.rc` file.  This will print a lot of extra information to the log file.  You can then see which log file was being read when the error occurred.

**Comment by Naaimaben** [comment] 2024-08-13 11:08
Thank you, @yantosca! I appreciate your guidance. The error is fixed thanks to the additional log information. I replaced the file `gmi.clim.HCFC141b.geos5.2x25.nc` that was downloaded from `https://ftp.as.harvard.edu/` with the file from `(http://geoschemdata.wustl.edu/ExtData/HEMCO/GMI/v2015-02/gmi.clim.HCFC141b.geos5.2x25.nc)`.

**Comment by yantosca** [comment] 2024-08-13 14:00
Thanks @Naaimaben for the update.  Glad the issue is fixed!  Sometimes you may find corrupted files due to incomplete data downloading (i.e. network issues in the middle of a download, etc.).  I'll close this out now.  Feel free to reach out again if you encounter further issues.

**Closed by yantosca** 2024-08-13 14:00 UTC
Labels: category: Bug, topic: Runtime Error
