### ISSUE TITLE
WetLossLS netcdf file doesn't open 

### ISSUE THREAD

**Issue by laura-hyesung-yang** [geoschem/geos-chem#1761] opened 2023-04-18 17:01 UTC
### Name and Institution (Required)

Name: Laura Yang
Institution: Harvard University

### Description of your issue or question

I'm trying to output the wet loss rate via rainout and washout in the large-scale wet deposition of MP species in GEOS-Chem version 13.3.4. I'm outputting only 'WetLossLS_MP' in the HISTORY.rc for the WetLossLS diagnostic. However, when I try to open the output "GEOSChem.WetLossLS.20160101_0000z.nc4" file, I get the error stating "can't recognize the format of input file GEOSChem.WetLossLS.20160101_0000.nc4. It's odd as I am able to output 'WetLossConv_MP' and open its related file without an issue. I believe file writing is the issue as the model runs successfully and other outputs are viewable. Below is the MP species information from 'species_database.yml'.

```yaml
MP:
  Background_VV: 4.0e-15
  Formula: CH3OOH
  FullName: Methyl hydro peroxide
  Henry_CR: 5200.0
  Henry_K0: 2.94e+2
  Is_Advected: true
  Is_Gas: true
  Is_Photolysis: true
  Is_WetDep: true
  MW_g: 48.05
  WD_RetFactor: 2.0e-2
```
Thank you!

**Comment by laura-hyesung-yang** [comment] 2023-04-19 14:50
I used to do a monthly output for WetLossLS and the file was corrupted. However, if I change it to a daily output, only the first date's netcdf file is corrupted and the netcdf files for the rest of the days are OK for the WetLossLS diagnostic.

**Comment by lizziel** [comment] 2023-04-19 18:11
Hi Laura, what software are you using to open the file? If you are running on Cannon could you point me to your run directory? I tried to reproduce the issue with 13.3.4 and was able to generate the files okay. Perhaps I have different settings than you.

**Comment by laura-hyesung-yang** [comment] 2023-04-20 00:10
Hi @lizziel, my run directory is `/n/holyscratch01/jacob_lab/lyang/GC/modified_model_nested_MPbudget/`. You can find the outputs under OutputDir and I copied the code directory for you, named '`CodeDir_copy/`. Thank you!

**Comment by lizziel** [comment] 2023-04-20 13:43
From the log it looks like there were four instances running GEOS-Chem at the same time, all started in the same minute. All of them wrote to the same log file, and all four were trying to create and write to the first WetLossLS diagnostic file at the same time. Three of the four failed and exited from the simulation. The fourth kept going but presumably the file got corrupted during write due to the other attempts to use the same. Do you know why there might have been four runs? I only see one slurm file which would indicate only one run.

**Comment by laura-hyesung-yang** [comment] 2023-04-20 17:03
Hi @lizziel, thanks for looking into it! I actually always get 4 core files out at the end of the run. But I submit my run using the geoschem.run file provided as the default. The code looks like the following: 
`# Set the proper # of threads for OpenMP
# SLURM_CPUS_PER_TASK ensures this matches the number you set with -c above
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

# Run GEOS_Chem.  The "time" command will return CPU and wall times.
# Stdout and stderr will be directed to the "GC.log" log file
# (you can change the log file name below if you wish)
source gcc.env
srun -c $OMP_NUM_THREADS time -p ./gcclassic >> GC.log
`
I will try to change the code so that I get 1 core at the end of the run and keep you posted if the problem persists.

**Comment by lizziel** [comment] 2023-04-20 18:41
I am closing out this issue since we were able to resolve the problem by moving `source gcc.env` in the run script to before the export of `OMP_NUM_THREADS`. Sourcing the environment file was overwriting the number of threads used from 32 to 8. This resulted in 4 simultaneous 8-core runs across the requested 32 nodes.

**Closed by lizziel** 2023-04-20 18:41 UTC
Labels: question
