### ISSUE TITLE
wet deposition error.

### ISSUE THREAD

**Issue by yutian8888** [geoschem/geos-chem#2077] opened 2023-12-18 20:09 UTC
### Name and Institution (Required)

Name: Yu Tian
Institution: Rutgers University

### Confirm you have reviewed the following documentation

- [x] [Support guidelines](https://geos-chem.readthedocs.io/en/stable/help-and-reference/SUPPORT.html)
- [x] [User manuals](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/related-docs.html)
- [x] [Debugging GEOS-Chem and HEMCO errors](https://geos-chem.readthedocs.io/en/stable/geos-chem-shared-docs/supplemental-guides/debug-guide.html)
- [x] [Current and past Github issues](https://github.com/geoschem/geos-chem/issues)

### Description of your issue or question

I set up a GC global run (version 14.1.1) from 2021.01 to 2022.12, my compiler version is GNC 7.3.0, and I didn't change any of the base code. I met this wet deposition issue on 2022/01/20. I checked #501, but I think the restart and emission is fine.
**error message:**
![image](https://github.com/geoschem/geos-chem/assets/147092225/09ef52d4-8b8e-4948-b7f0-1139917eaa19)

**setting files and log file**
[geoschem_config.yml.txt](https://github.com/geoschem/geos-chem/files/13708107/geoschem_config.yml.txt)
[HISTORY.rc.txt](https://github.com/geoschem/geos-chem/files/13708108/HISTORY.rc.txt)
[HEMCO_Config.rc.txt](https://github.com/geoschem/geos-chem/files/13708109/HEMCO_Config.rc.txt)
[GC.2022.01.01.log1.txt](https://github.com/geoschem/geos-chem/files/13708121/GC.2022.01.01.log1.txt)
[GC.2022.01.01.log2.txt](https://github.com/geoschem/geos-chem/files/13708122/GC.2022.01.01.log2.txt)

**Comment by yantosca** [comment] 2023-12-18 21:51
Thanks for writing @yutian8888.  I think the wetdep error is a side-effect of some non-convergence issues in the chemistry:

```console
 T=   4.8000000000000140E-048 and H=   4.8000000000000140E-048
 ### INTEGRATE RETURNED ERROR AT:          138          65           8
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   2.0086890860013807E-048 and H=   2.0086890860013807E-048
 ### INTEGRATE RETURNED ERROR AT:            9          68           8
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   8.9327508533268695E-033 and H=   8.9327508533268695E-033
 ### INTEGRATE RETURNED ERROR AT:           91          65           8
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   1.5637153431685461E-018 and H=   1.5637153431685461E-018
 ### INTEGRATE RETURNED ERROR AT:           22          63           8
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   3.0648103885212306E-032 and H=   3.0648103885212306E-032
 ### INTEGRATE RETURNED ERROR AT:          128          68           8
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   9.2372456237730852E-032 and H=   9.2372456237730852E-032
 ### INTEGRATE RETURNED ERROR AT:           93          64           8
 Forced exit from Rosenbrock due to the following error:
 --> Step size too small: T + 10*H = T or H < Roundoff
 T=   3.0643924693808403E-019 and H=   3.0643924693808403E-019
 ### INTEGRATE RETURNED ERROR AT:          118          63           8
```
Did you run GEOS-Chem "out-of-the-box", or were any modifications made to the code.  You could try running a short simulation with `-DCMAKE_BUILD_TYPE=Debug` in order to check for any errors like arrays out-of-bounds or floating point overflow/underflow.

**Comment by yutian8888** [comment] 2023-12-21 02:34
> Thanks for writing @yutian8888. I think the wetdep error is a side-effect of some non-convergence issues in the chemistry:
> 
> ```
>  T=   4.8000000000000140E-048 and H=   4.8000000000000140E-048
>  ### INTEGRATE RETURNED ERROR AT:          138          65           8
>  Forced exit from Rosenbrock due to the following error:
>  --> Step size too small: T + 10*H = T or H < Roundoff
>  T=   2.0086890860013807E-048 and H=   2.0086890860013807E-048
>  ### INTEGRATE RETURNED ERROR AT:            9          68           8
>  Forced exit from Rosenbrock due to the following error:
>  --> Step size too small: T + 10*H = T or H < Roundoff
>  T=   8.9327508533268695E-033 and H=   8.9327508533268695E-033
>  ### INTEGRATE RETURNED ERROR AT:           91          65           8
>  Forced exit from Rosenbrock due to the following error:
>  --> Step size too small: T + 10*H = T or H < Roundoff
>  T=   1.5637153431685461E-018 and H=   1.5637153431685461E-018
>  ### INTEGRATE RETURNED ERROR AT:           22          63           8
>  Forced exit from Rosenbrock due to the following error:
>  --> Step size too small: T + 10*H = T or H < Roundoff
>  T=   3.0648103885212306E-032 and H=   3.0648103885212306E-032
>  ### INTEGRATE RETURNED ERROR AT:          128          68           8
>  Forced exit from Rosenbrock due to the following error:
>  --> Step size too small: T + 10*H = T or H < Roundoff
>  T=   9.2372456237730852E-032 and H=   9.2372456237730852E-032
>  ### INTEGRATE RETURNED ERROR AT:           93          64           8
>  Forced exit from Rosenbrock due to the following error:
>  --> Step size too small: T + 10*H = T or H < Roundoff
>  T=   3.0643924693808403E-019 and H=   3.0643924693808403E-019
>  ### INTEGRATE RETURNED ERROR AT:          118          63           8
> ```
> 
> Did you run GEOS-Chem "out-of-the-box", or were any modifications made to the code. You could try running a short simulation with `-DCMAKE_BUILD_TYPE=Debug` in order to check for any errors like arrays out-of-bounds or floating point overflow/underflow.

Thanks for replying @yantosca, I run GEOS-Chem "out-of-the-box" and did not make any modifications to the code. I only see '-DCMAKE_RELEASE_TYPE=Debug' on GC debug instruction files. I'm not sure if it is the same as `-DCMAKE_BUILD_TYPE=Debug`. I am new in GEOS-Chem, sorry for stupid questions. Besides, I saw this bug fix #1698 guideline, the problem is that it seems to be used to fix the nan value problem at "WASHOUT: at surface", mine issue is "RESUSPENSION in middle levels". I'm not that sure if it will work, but I will give it a try and report the result.

**Comment by yutian8888** [comment] 2023-12-23 18:29
Just a report to this issue. I checked the emission data, met data and restart data, there seems no NaN or strange value in it. And I tried the https://github.com/geoschem/geos-chem/pull/1698, it turned out the issue was not fixed, the error was exactly the same as the former one.

**Comment by yutian8888** [comment] 2024-01-02 16:01
I revised the code at Do_Complete_Reevap (in module GeosCore/wetscav_mod.F90) to be :
![Pasted Graphic 7](https://github.com/geoschem/geos-chem/assets/147092225/bde0dd0c-c377-4459-b3d3-024b5b3c9ff7)
But the result shows that there is still nan value errors, but at DO_RAINOUT_ONLY this time:
![image](https://github.com/geoschem/geos-chem/assets/147092225/9a7802bd-cf32-4e22-931f-c94e7837e73c)
I'm not sure if I should do the similar revise as what I do at Do_Complete_Reevap. Or maybe I should just change the model tolerance? If anyone has suggestion, please feel free to give me.

**Comment by yantosca** [comment] 2024-01-02 16:13
@yutian8888: Wondering if the species concentrations are NaN before even getting into wetdep?  You can try to turn off operations (i.e. wetdep, drydep, transport, chemistry) one at a time to see if you can isolate the operation where the problem occurs.

**Comment by yutian8888** [comment] 2024-01-02 17:11
@yantosca thank you for your response. I plan to try turning off operations one by one to isolate the issue.

I wanted to provide an update on the debugging process. I used the -DCMAKE_BUILD_TYPE=Debug flag for compiling, and I've encountered the following output, which I'm unsure how to interpret:

<img width="482" alt="image" src="https://github.com/geoschem/geos-chem/assets/147092225/683acaee-e310-43d2-9ddf-c56fb7dc7c75">

Could you help me understand what this might indicate?

**Comment by yantosca** [comment] 2024-01-02 18:56
Thanks @yutian8888.  Could you post the entire log?  

The issue is at hco_interp_a2a_mod.F90 at line 1383.  That's what is indicated in the first entry (#0) in the traceback output. The #0 is the place of the error and #1 is the routine it was called from, #2 is the routine where #1 was called from, etc.

**Comment by yutian8888** [comment] 2024-01-02 19:12
> Thanks @yutian8888. Could you post the entire log?
> 
> The issue is at hco_interp_a2a_mod.F90 at line 1383. That's what is indicated in the first entry (`#0`) in the traceback output. The `#0` is the place of the error and `#1` is the routine it was called from, `#2` is the routine where `#1` was called from, etc.

Thanks for your explanation @yantosca, here I attached the log file.
[GC.2022.01.01.log](https://github.com/geoschem/geos-chem/files/13813185/GC.2022.01.01.log)
Is there any chance that the emission data file 'biovoc_025.20220120.nc' is broken:
![image](https://github.com/geoschem/geos-chem/assets/147092225/f4619fea-9a93-42b7-a7ec-a67a5cc0c797)

**Comment by yantosca** [comment] 2024-01-02 21:10
Thanks for catching this @yutian8888.  Indeed the offline emissions for 2022/01/20 are corrupted.  If you use ncview or panoply to view these files, then it seems that the data for 1600z is corrupted (you get a white screen and not a plot).

I will close this issue and open a new issue for corrupted data.

**Comment by yantosca** [comment] 2024-01-02 21:21
Closing this issue, discussion has moved to #2093

**Closed by yantosca** 2024-01-02 21:21 UTC
Labels: bug, KPP / chem mechanisms, runtime
