### ISSUE TITLE
roundoff_mod.F90 (unit = 5, file = 'stdin') Fortran runtime error: End of file

### ISSUE THREAD

**Issue by samanehashraf** [geoschem/geos-chem#2565] opened 2024-11-08 15:29 UTC
### Your name

Samaneh

### Your affiliation

Research Associate

### What happened? What did you expect to happen?

Hi,
 I am trying to run GC-Classic version 14.4.3 to simulate data for 2023, but I encountered an error related to the Fortran code. Could you help me understand what might be causing this problem?

### What are the steps to reproduce the bug?

[geoschem_config.yml.txt](https://github.com/user-attachments/files/17680676/geoschem_config.yml.txt)
[Slurm.txt](https://github.com/user-attachments/files/17680677/Slurm.txt)

### What GEOS-Chem version were you using?

14.4.3

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

?

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

global 2*2.5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment] 2024-11-12 17:06
Duplicate of #2567

**Closed by yantosca** 2024-11-12 17:06 UTC
Labels: category: Bug
