### ISSUE TITLE
Error about AFCID when running nested simulation

### ISSUE THREAD

**Issue by Alex-Fang66** [geoschem/geos-chem#798] opened 2021-07-28 12:23 UTC
### Description of the problem
I created a clean run_dir (05x0625 nested of AS) and didn't change anything except file path and simulation time, which I don't think it would make any influence on simulation. However, I soon encountered an error and once I closed AFCID, the error disappeared. The error is shown below.
![sub message](https://user-images.githubusercontent.com/65645232/127319521-c923e59d-23d0-4f31-ac0c-08af44fa8995.png)

### Description of troubleshooting performed
I found something a little strange in HEMCO_Config.rc, I don't know why this sentence isn't concluded in the AFCID.
![AFCID_CHINA](https://user-images.githubusercontent.com/65645232/127320315-dce33f7a-bb77-4f7c-9025-5f2730779a28.png)
So I tried to include the '1009 CHINA_MASK  $ROOT/MASKS/v2018-09/China_mask.generic.1x1.nc                MASK ...' to the AFCID, but it didn't make any change. 

### GEOS-Chem version
GCClassic 13.1.0

### Software versions
- CMake version: cmake@3.16.1
- Compilers (Intel or GNU, and version): GNU gcc@9.3.0
- NetCDF version: netcdf-fortran@4.5.3

**Comment by lizziel** [comment] 2021-07-28 18:43
Hi @Alex-Fang66, could you provide the full configuration and log files for your run? You can add '.txt' to the filename and then drag and drop into the comment box on this page. Files to include are input.geos, HEMCO_Config.rc, HEMCO.log, the and GEOS-Chem standard output log.

**Comment by Alex-Fang66** [comment] 2021-07-29 01:08
@lizziel Sure, thanks a lot for relying. 
[input_geos.txt](https://github.com/geoschem/geos-chem/files/6897228/input_geos.txt)
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/6897229/HEMCO_Config.txt)
[GC.txt](https://github.com/geoschem/geos-chem/files/6897230/GC.txt)
[HEMCO_log.txt](https://github.com/geoschem/geos-chem/files/6897231/HEMCO_log.txt)

**Comment by Alex-Fang66** [comment] 2021-07-30 14:34
Thanks a lot!  I am looking forward it.

**Comment by yantosca** [comment] 2021-07-30 16:57
@Alex-Fang66 @lizziel, I have pushed a fix for this issue to commit 419831b62e2544bcfae268989216810fced62fe1.  The problem was in this line of code in `GeosUtil/gc_grid_mod.F90`:
```F90
       ! Compute the last longitude edge
       IF ( I == State_Grid%NX ) THEN
          State_Grid%XEdge(I+1,J) = State_Grid%GlobalXEdge(I+1,J)
       ENDIF
```
The problem is that the `State_Grid%GlobalXedge` array should be using the `IG` index, which is the global grid index, instead of `I`, which is the cropped grid index.  So you can change this line in your code to:
```
       ! Compute the last longitude edge
       IF ( I == State_Grid%NX ) THEN
          State_Grid%XEdge(I+1,J) = State_Grid%GlobalXEdge(IG+1,J)
       ENDIF
```
and you should be able to get past the AFCID error. 

I have also pushed commit 419831b62e2544bcfae268989216810fced62fe1 to the branch `patch/13.2.1` on Github, and we will ship this with version 13.2.1 (since 13.2.0 is in the benchmarking process now).  13.2.1 will be released immediately after 13.2.0.

This error came in with the updates for the GCAP2 met fields (see commit https://github.com/geoschem/geos-chem/pull/670/files#diff-6bef98c96bbd568f6506ec8bccd7cccac460730fc6b92c32f837bad0715a7073)

**Comment by yantosca** [comment] 2021-07-30 17:00
Also noting that this is the same issue described in #788

**Comment by yantosca** [comment] 2021-07-30 19:34
I've confirmed that the fix mentioned above now allows nested-grid simulations to proceed without encountering the AFCID regridding error.  I will close this issue now.  Thanks for bringing it up @Alex-Fang66.

**Closed by yantosca** 2021-07-30 19:34 UTC
Labels: bug, duplicate
