### ISSUE TITLE
[BUG/ISSUE] Excessive fall velocity in UCX when running complex SOA_SVPOA

### ISSUE THREAD

**Issue by yangning-code** [geoschem/geos-chem#946] opened 2021-10-09 11:10 UTC
### Description of the problem
When I use GEOS-Chem.13.2.1 to run gc_025x03125_geosfp_fullchem_complexSOA, The model always reports an error, the content is as follows GEOS-CHEM ERROR:  Excessive fall velocity? STOP at  CALC_FALLVEL, UCX_mod. The specific content is placed in the log files

### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

### GEOS-Chem version
GEOS-Chem.13.2.1

### Description of modifications
default

### Log files
- Build log (if applicable):
- Run logs (if applicable):
- Run script (if applicable):
[1712.log](https://github.com/geoschem/geos-chem/files/7315468/1712.log)

### Software versions
- CMake version:cmake version 3.21.3
- Compilers (Intel or GNU, and version):ifort (IFORT) 17.0.5 20170817
- NetCDF version:netcdf-4.6.1-withhdf5

**Comment by yantosca** [comment] 2021-10-12 13:52
This may be duplicate of #762.

**Comment by yantosca** [comment] 2021-10-15 15:10
@yangning-code, did applying the fix in #762 solve your issue?

**Comment by yangning-code** [comment] 2021-10-18 00:23
I can only modify the falling speed threshold to keep the model running.

**Comment by yangning-code** [comment] 2021-10-30 03:30
Is there no way to solve this problem?

**Closed** 2021-11-01 11:15 UTC
Labels: bug, duplicate

**Comment by twszhymym163** [comment] 2022-12-17 13:15
> 

Has the problem been solved?
