### ISSUE TITLE
few  new questions

### ISSUE THREAD

**Issue by rongbing0353** [geoschem/geos-chem#2597] opened 2024-11-27 06:26 UTC
### Your name

runbin

### Your affiliation

lanzhou university

### What happened? What did you expect to happen?

Hello everyone,

I would like to add a new PM2.5 inventory in HEMCO and have the following questions that I hope you can help me with:

If I have a global scale inventory of 0.5 degrees by 0.5 degrees, can I directly simulate it in GEOS-Chem? I saw in the GEOS-Chem guidelines that a resolution of 0.5 by 0.625 degrees is only used in nested areas, which means nested within 2 by 2.5 degrees? But can't I use a 0.5 by 0.625 degrees resolution to simulate the global scale directly? I am very confused.

The meteorological data I am using is MERRA2, which I see in HEMCO is at a 2 by 2.5 degrees resolution. Do I have to convert it to 0.5 by 0.625 degrees to simulate? Or do I not need to change it? Also, the resolution of the chemical module and the restart files is not 0.5 by 0.625 degrees; do I need to change them all to 0.5 by 0.625 degrees to simulate?

My resolution is 0.5 by 0.5; can it be equivalent to 0.5 by 0.625, without the need for resolution conversion?

I am not clear about the concept of "scaling factor". Where is it used exactly? I don't understand it at all.

The files generated by my dry-run cannot be downloaded. What could be the reason?

Thank you for your help.

Best regards.

### What are the steps to reproduce the bug?

Hello everyone,

I would like to add a new PM2.5 inventory in HEMCO and have the following questions that I hope you can help me with:

If I have a global scale inventory of 0.5 degrees by 0.5 degrees, can I directly simulate it in GEOS-Chem? I saw in the GEOS-Chem guidelines that a resolution of 0.5 by 0.625 degrees is only used in nested areas, which means nested within 2 by 2.5 degrees? But can't I use a 0.5 by 0.625 degrees resolution to simulate the global scale directly? I am very confused.

The meteorological data I am using is MERRA2, which I see in HEMCO is at a 2 by 2.5 degrees resolution. Do I have to convert it to 0.5 by 0.625 degrees to simulate? Or do I not need to change it? Also, the resolution of the chemical module and the restart files is not 0.5 by 0.625 degrees; do I need to change them all to 0.5 by 0.625 degrees to simulate?

My resolution is 0.5 by 0.5; can it be equivalent to 0.5 by 0.625, without the need for resolution conversion?

I am not clear about the concept of "scaling factor". Where is it used exactly? I don't understand it at all.

The files generated by my dry-run cannot be downloaded. What could be the reason?

Thank you for your help.

Best regards.

### What GEOS-Chem version were you using?

13.0.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc10.2

### Will you be addressing this bug yourself?

Yes, but I will need some help

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

0.5*0.625

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment] 2024-12-02 20:18
This is a duplicate of issue #2598.  Please see the answers in this issue.

**Closed** 2024-12-02 20:18 UTC
Labels: duplicate
