### ISSUE TITLE
[BUG/ISSUE] Segmentation fault after TPCORE

### ISSUE THREAD

**Issue by lfreese** [geoschem/geos-chem#177] opened 2019-12-13 20:54 UTC
Using v12.3.2 I am running a nested grid NA .5x.625 and am getting a segmentation fault when the previously generated boundary conditions are loaded in. I am using ifort17 as a compiler, and am running this on a cluster.I have set my OMP_STACKSIZE = 500m 

## Compiling the run
To build I run realclean first since I was using GEOS-FP before and am using MERRA2 now.

 `make -j4 CODE_DIR=/net/fs11/d0/emfreese/GEOS_CHEM/Code.12.3.2/ realclean`

` make -j4 CODE_DIR=/net/fs11/d0/emfreese/GEOS_CHEM/Code.12.3.2/ mpbuild`

after which I submit this to our queue via `sbatch gc_input.sh`
## Expected output
I expect it to run as I have specified the new boundary condition outputs, and given it a large stacksize and memory limit. However, it keeps hitting a segmentation error when it starts reading in the new boundary conditions, something I assume is a space problem.

## Error messages
my_run.err returns:
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libintlc.so.5      00002B7D43DD9BF1  tbk_trace_stack_i     Unknown  Unknown
libintlc.so.5      00002B7D43DD7D2B  tbk_string_stack_     Unknown  Unknown
libifcoremt.so.5   00002B7D42077AC2  Unknown               Unknown  Unknown
libifcoremt.so.5   00002B7D42077916  tbk_stack_trace       Unknown  Unknown
libifcoremt.so.5   00002B7D41FD0AB0  for__issue_diagno     Unknown  Unknown
libifcoremt.so.5   00002B7D41FE2658  for__signal_handl     Unknown  Unknown
libpthread-2.23.s  00002B7D4403DC20  Unknown               Unknown  Unknown
geos.mp            000000000060AB43  tpcore_bc_mod_mp_        1060  tpcore_bc_mod.F

Stack trace terminated abnormally.

real    2m48.643s
user    33m22.746s
sys     1m17.439s
```

my_run.out returns:
```NASA-GSFC Tracer Transport Module successfully initialized
     - OPEN_BC_FILE: Opening /net/fs11/d0/emfreese/GCrundirs/type_global-out_bc/geosfp_2x25_standard/BC_2x25_NA/BC.20150801 on unit   14
     - READ_WINDOW_TPCORE_BC: Found all 145 BC's at 2015/08/01 00:00
```

## Input and log files attached
[HEMCO_Config.txt](https://github.com/geoschem/geos-chem/files/3962679/HEMCO_Config.txt)
[HEMCO.log.txt](https://github.com/geoschem/geos-chem/files/3962680/HEMCO.log.txt)
[input.geos.txt](https://github.com/geoschem/geos-chem/files/3962681/input.geos.txt)
[lastbuild.mp.txt](https://github.com/geoschem/geos-chem/files/3962682/lastbuild.mp.txt)
[my_run-173188.err.txt](https://github.com/geoschem/geos-chem/files/3962683/my_run-173188.err.txt)
[my_run-173188.out.txt](https://github.com/geoschem/geos-chem/files/3962684/my_run-173188.out.txt)
[gc_run.sh.txt](https://github.com/geoschem/geos-chem/files/3962691/gc_run.sh.txt)

## Additional context
The wiki page for dealing with segmentation problems says to increase the OMP_STACKSIZE and ulimit -s unlimit, but these are both already done in my gc_run.sh file attached, so I am not sure what to do.

**Comment by yantosca** [comment] 2019-12-13 21:09
Thanks for writing.  This line of output:
```
geos.mp            000000000060AB43  tpcore_bc_mod_mp_        1060  tpcore_bc_mod.F
```
indicates that the error happened at line 1060 of tpcore_bc_mod.F.  You can go there to see what that line is.  I wonder if there is a problem the data file being corrupted.

**Comment by lfreese** [comment] 2019-12-16 14:45
The line there is just:

```
  END SUBROUTINE DO_WINDOW_TPCORE_BC
```
which is a part of the section:

```
      !=================================================================
      ! Copy the BC data into the proper elements of Spc
      !
      ! NOTE: We assume that we have saved 4x5 BC's from a global
      ! GEOS-CHEM run.  It takes too long to save the 2x25 BC's.
      ! One may always another subroutine for 2x25 BC's later.
      !=================================================================
```

I'm wondering if my BC files are corrputed?

**Comment by yantosca** [comment] 2019-12-16 20:57
Hi Lyssa -- can you read in the BC files with GAMAP to make sure that they are the same resolution as you expect?

**Comment by yantosca** [comment] 2019-12-16 21:22
Also -- I noticed that the BC's are from a geosfp_2x25_standard run (which has 72 levels).  But your lastbuild file has "tropchem" listed as the chemical mechanism (which has 47 levels).  This most certainly is the cause of the seg fault -- it is trying to read too much data from disk and the data is getting garbled, or hitting an invalid memory location.

With 12.3.2, the boundary conditions have to match the vertical grid of the global simulation.  You should always use the same chemical mechansim in the global and nested simulations so that the boundary conditions will be on the same vertical grid.

In 12.4.0 (I believe) and later versions, we use HEMCO to read netCDF boundary conditions, so it can regrid in the vertical if there is a grid mismatch.  But it's always safest to use the same mechanism (tropchem, standard) in the global run as in the nested run.

**Comment by lfreese** [comment] 2019-12-18 15:21
I see--I'm trying again and updating to use 12.6.1 since it has the Flexgrid. I'll use MERRA2 for both of the runs in this so I don't run into this issue again.

**Comment by yantosca** [comment] 2019-12-18 15:37
Thanks Lyssa.  Let us know if you run into any other issues.  I'll go ahead and close this issue out now.

**Comment by lfreese** [comment] 2019-12-18 17:55
Hi Bob, to follow up on the questions and your explanation above, if I am creating the nested run and want it to be standard rather than tropchem, that doesn't seem to be an option in the nested model run selections:

```
## ======= Nested model runs ==================================================
# merra2   05x0625     as     tropchem         2016070100   2016080100     -
# merra2   05x0625     na     tropchem         2013120100   2015010100     -
# geosfp   025x03125   ch     tropchem         2016070100   2016080100     -
# geosfp   025x03125   na     tropchem         2016070100   2016080100     -
```
as these are all set to tropchem. If I change it to read `# merra2   05x0625     na     standard         2013120100   2015010100     -` instead there are no run files for merra2 standard 05x0625 NA in the runs section of UT.

**Comment by yantosca** [comment] 2019-12-18 18:20
Hi Lyssa.  I think that is because the nested simulations typically use tropchem for computational efficiency.  Because the horizonal resolution is so small, we typically use a reduced vertical resolution (47 layers).

If you are using 12.6.1 (FlexGrid enabled) you could request using the standard mechanism in the SIMULATION MENU:

```
%%% SIMULATION MENU %%% :
Start YYYYMMDD, hhmmss  : 20160701 000000
End   YYYYMMDD, hhmmss  : 20160701 010000
Run directory           : ./
Root data directory     : /n/holylfs/EXTERNAL_REPOS/GEOS-CHEM/gcgrid/data/ExtData
Met field               : geosfp
Simulation name         : standard
Turn on debug printout? : F
```

I think you would also need to compile with the CHEM=Standard option. 

@msulprizio am I forgetting any other settings to change?

**Comment by lfreese** [comment] 2019-12-18 18:28
I see. Right now I can use a tropchem instead for the runs, but when I run just tropchem (either the global or the nested, I get this error, which seems to be with my compiler):

```
OMP: Error #133: Inconsistent THREADPRIVATE common block declarations are non-conforming and are unsupported. Either all threadprivate common blocks must be declared identically, or the largest instance of each threadprivate common block must be referenced first during the run.
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source
libintlc.so.5      00002B255624CBF1  tbk_trace_stack_i     Unknown  Unknown
libintlc.so.5      00002B255624AD2B  tbk_string_stack_     Unknown  Unknown
libifcoremt.so.5   00002B25544EAAC2  Unknown               Unknown  Unknown
libifcoremt.so.5   00002B25544EA916  tbk_stack_trace       Unknown  Unknown
libifcoremt.so.5   00002B2554443AB0  for__issue_diagno     Unknown  Unknown
libifcoremt.so.5   00002B25544558A0  for__signal_handl     Unknown  Unknown
libpthread-2.23.s  00002B25564B0C20  Unknown               Unknown  Unknown
libc-2.23.so       00002B25568F4738  gsignal               Unknown  Unknown
libc-2.23.so       00002B25568F634A  abort                 Unknown  Unknown
libiomp5.so        00002B2555F1B3E3  Unknown               Unknown  Unknown
libiomp5.so        00002B2555F09111  Unknown               Unknown  Unknown
libiomp5.so        00002B2555F3F958  __kmpc_threadpriv     Unknown  Unknown
libiomp5.so        00002B2555F3F6C1  __kmpc_threadpriv     Unknown  Unknown
geos               0000000000B9AEA9  gckpp_initialize_          40  gckpp_Initialize.F90
geos               00000000007FF195  flexchem_mod_mp_d         857  flexchem_mod.F90
libiomp5.so        00002B2555F43D13  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002B2555F13B17  Unknown               Unknown  Unknown
libiomp5.so        00002B2555F131C5  Unknown               Unknown  Unknown
libiomp5.so        00002B2555F44193  Unknown               Unknown  Unknown
libpthread-2.23.s  00002B25564A75CA  Unknown               Unknown  Unknown
libc-2.23.so       00002B25569C30CD  clone                 Unknown  Unknown
/tmp/slurmd/job173677/slurm_script: line 50: 26554 Aborted                 (core dumped) ${exepath}
```

I tried to fix it by changing the thread size and looking at the lines at which the error is occuring in gckpp_Initialize.F90 which is: 
`SUBROUTINE Initialize ( )`

and in flexchem_mod.F90 it is:
```
       !====================================================================
       ! Intialize KPP solver arrays: CFACTOR, VAR, FIX, etc.
       !====================================================================
       CALL Init_KPP( )
```

But increasing the OMP_STACKSIZE even to 600m doesn't help. I haven't found any solutions for this error in previous documentation either.

**Comment by yantosca** [comment] 2020-01-02 17:39
Happy New Year!  I am looking at the error you reported above:
```
OMP: Error #133: Inconsistent THREADPRIVATE common block declarations
are non-conforming and are unsupported. Either all threadprivate common
blocks must be declared identically, or the largest instance of each threadprivate
common block must be referenced first during the run.
forrtl: error (76): Abort trap signal
```
So this is referring to the THREADPRIVATE declarations in the gckpp_Global.F90 file:
```
MODULE gckpp_Global

  USE gckpp_Parameters, ONLY: dp, NSPEC, NVAR, NFIX, NREACT
  PUBLIC
  SAVE


! Declaration of global variables

! C - Concentration of all species
  REAL(kind=dp) :: C(NSPEC)
! VAR - Concentrations of variable species (global)
  REAL(kind=dp) :: VAR(NVAR)
! FIX - Concentrations of fixed species (global)
  REAL(kind=dp) :: FIX(NFIX)
! VAR, FIX are chunks of array C
!      EQUIVALENCE( C(1),VAR(1) )
!      EQUIVALENCE( C(221),FIX(1) )
! RCONST - Rate constants (global)
  REAL(kind=dp) :: RCONST(NREACT)
! TIME - Current integration time
  REAL(kind=dp) :: TIME
! SUN - Sunlight intensity between [0,1]
  REAL(kind=dp) :: SUN
! TEMP - Temperature
  REAL(kind=dp) :: TEMP
! RTOLS - (scalar) Relative tolerance
  REAL(kind=dp) :: RTOLS
! TSTART - Integration start time
  REAL(kind=dp) :: TSTART
! TEND - Integration end time
  REAL(kind=dp) :: TEND
! DT - Integration step
  REAL(kind=dp) :: DT
! ATOL - Absolute tolerance
  REAL(kind=dp) :: ATOL(NVAR)
! RTOL - Relative tolerance
  REAL(kind=dp) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  REAL(kind=dp) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(kind=dp) :: STEPMAX
! CFACTOR - Conversion factor for concentration units
  REAL(kind=dp) :: CFACTOR

! INLINED global variable declarations

      REAL(kind=dp) :: HET(NSPEC,7), PHOTOL(1000)
      REAL(kind=dp) :: NUMDEN, H2O, PRESS

!-----------------------------------------------------------------------
! NOTE: The following variables need to be declared THREADPRIVATE
! because they get written to within an OpenMP parallel loop
!-----------------------------------------------------------------------
!$OMP THREADPRIVATE( C,       VAR, FIX,    RCONST, TIME, TEMP  )
!$OMP THREADPRIVATE( CFACTOR, HET, PHOTOL, NUMDEN, H2O,  PRESS )
```
I wonder if this is because you haven't done a "make realclean" or "make superclean".  If your source code still has code hanging around from a prior build, you might need to clean it first before recompiling.  Try that and see if it gets past this error.

**Comment by lfreese** [comment] 2020-01-05 15:55
Hi! Thanks so much--this was the case and it is now running.

**Comment by yantosca** [comment] 2020-01-06 14:52
Great!  I'll close out this issue now.

**Closed by yantosca** 2020-01-06 14:52 UTC
Labels: bug
