### ISSUE TITLE
Segmentation fault and Photolysis module 

### ISSUE THREAD

**Issue by fengfeng-6** [geoschem/geos-chem#2640] opened 2024-12-16 07:15 UTC
### Your name

jinquan ye

### Your affiliation

SJTU

### What happened? What did you expect to happen?

When I opened the photolysis module running program will be wrong, but when I close the photolysis module error disappeared, and it can run smoothly finally get "GEOSChem. SpeciesConc. 20190701 _0000z nc4", but in the end there will be an error:
```console
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NF90_Def_Var: can not create compressed variable : time

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NcDef_var_attributes_c: can not define attribute : long_name

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

### What are the steps to reproduce the bug?

In addition to closing the photolysis module, the two operations are as follows:
./gcclassic > GC.log 2>&1 

### Please attach any relevant configuration and log files.

The GC.log(1) file is the log file when I do not close the photolysis module, and the GC.log file is the log file after I close the photolysis module. The rest files are the same.
[log_and_other_file.zip](https://github.com/user-attachments/files/18146181/log_and_other_file.zip)

### What GEOS-Chem version were you using?

14.5.0

### What environment were you running GEOS-Chem on?

Personal computer

### What compiler and version were you using?

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### Will you be addressing this bug yourself?

Yes

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

4x5

### What meterology fields did you use?

MERRA-2

### Additional information

When I debug the photolysis module in debug mode, follow the following steps:
gdb gcclassic
run
The following error occurs:
```console
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
* B e g i n   T i m e   S t e p p i n g !!  *
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

---> DATE: 2019/07/01  UTC: 00:00
HEMCO already called for this timestep. Returning.
Getting CH4 boundary conditions in GEOS-Chem from :NOAA_GMD_CH4
HEMCO (VOLCANO):  Opening /root/autodl-tmp/ExtData/HEMCO/VOLCANO/v2024-04/2019/07/so2_volcanic_emissions_Carns.20190701.rc

Thread 1 "gcclassic" received signal SIGSEGV, Segmentation fault.
0x000056548dc85514 in cldj_fjx_sub_mod::opmie (dtaux=... , pomegax=... , u0=0.90416587805398996, rfl=... , amf=... , amg=... , jxtra=... , fjact=... , fjtop=... , fjbot=... , fibot=... , fsbot=... , fjflx=... , flxd=... , flxd0=... , ldokr=... , lu=72, rc=0, ldokr=...)  at /root/gc_4x5_merra2_fullchem/CodeDir/src/Cloud-J/src/Core/cldj_fjx_sub_mod.F90:796
796           subroutine OPMIE (DTAUX,POMEGAX,U0,RFL,AMF,AMG,JXTRA, &
```

**Comment by fengfeng-6** [comment] 2024-12-16 07:16
@yantosca

**Comment by yantosca** [comment] 2024-12-16 15:05
Thanks for writing @fengfeng-6.  This error could be caused by a couple of things:

1. You might have compiled GEOS-Chem with a different compiler than what was used to build the netCDF library.
2. You ran out of disk space or the file is write-protected.

**Comment by yantosca** [comment] 2024-12-17 15:32
@fengfeng-6: I think the issue is not to do with memory but disk space.
```console
---> DATE: 2019/07/01  UTC: 23:50
     - Creating file for SpeciesConc; reference = 20190701 000000
        with filename = OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NF90_Def_Var: can not create compressed variable : time

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

NcDef_var_attributes_c: can not define attribute : long_name

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 

This is an error that was encountered in one of the netCDF I/O modules,
which indicates an error in writing to or reading from a netCDF file!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Your run got all the way to the end but it couldn't write a netCDF file.  Please check that you didn't fill up all of the available space on your disk (or that the `OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4`file is not write-protected, and thus cannot be overwritten).

**Comment by fengfeng-6** [comment] 2024-12-18 07:48
> @fengfeng-6: I think the issue is not to do with memory but disk space.
> 
> ```
> ---> DATE: 2019/07/01  UTC: 23:50
>      - Creating file for SpeciesConc; reference = 20190701 000000
>         with filename = OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> NF90_Def_Var: can not create compressed variable : time
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> NcDef_var_attributes_c: can not define attribute : long_name
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> Code stopped from DO_ERR_OUT (in module NcdfUtil/m_do_err_out.F90) 
> 
> This is an error that was encountered in one of the netCDF I/O modules,
> which indicates an error in writing to or reading from a netCDF file!
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> ```
> 
> Your run got all the way to the end but it couldn't write a netCDF file. Please check that you didn't fill up all of the available space on your disk (or that the `OutputDir/GEOSChem.SpeciesConc.20190701_0000z.nc4`file is not write-protected, and thus cannot be overwritten).

Dear @yantosca :thank you for you patient reply. I have a lot of space on my disk, and ` OutputDir/GEOSChem SpeciesConc. 20190701 _0000z nc4 ` file is writable and dosen't use much space , may not be caused by the two problems, the following is the picture of the memory of my disk and file:
![71aeeeedfdd60087d96a121a3f3a7c5](https://github.com/user-attachments/assets/1797ec85-777f-4e89-b4af-09bfd74f2334)
![image](https://github.com/user-attachments/assets/bdba18c2-74ff-411c-870a-dd945800d92d)
![image](https://github.com/user-attachments/assets/03cd2fd6-915d-4cb2-bff8-fccbec5e45c2)
The last image is the memory usage monitoring after I turned off the photolysis module. what can i do to check the problem?

**Comment by yantosca** [comment] 2024-12-18 15:14
@fengfeng-6 You said you are using a personal computer, right?  I think you would have better luck if you tried to run GEOS-Chem on a computer cluster or on the AWS cloud.  The specifics of your machine might not support running the GEOS-Chem full-chemistry simulation.

**Comment by fengfeng-6** [comment] 2024-12-19 03:52
> @fengfeng-6 You said you are using a personal computer, right? I think you would have better luck if you tried to run GEOS-Chem on a computer cluster or on the AWS cloud. The specifics of your machine might not support running the GEOS-Chem full-chemistry simulation.

Thank you for your suggestion! @yantosca  I will try to run GEOS-Chem on a computer cluster

**Comment by yantosca** [comment] 2024-12-19 14:39
No problem @fengfeng-6.  GEOS-Chem probably can't be run on a Linux computer (unless you are doing one of the specialty simulations with a very small memory footprint).  Always best to run on a cluster or on an EC2 instance on the AWS cloud. 

I'll close this out.  Thanks again!

**Closed by yantosca** 2024-12-19 14:39 UTC
Labels: category: Bug, topic: Runtime Error
