### ISSUE TITLE
Satellite diagnostic simulations show a gradual decrease in pressure day by day

### ISSUE THREAD

**Issue by zpleo** [geoschem/geos-chem#2478] opened 2024-09-26 05:50 UTC
### Your name

Zhang Peng

### Your affiliation

Southern University of Science and Technology

### Please provide a clear and concise description of your question or discussion topic.

I opened the satellite transit simulation in HISTORY.rc and set daily diagnostic output, but when I checked the SatDiagnPEdge in the output file, I found that the pressure of the first level of each day gradually decreased. The first day of each month was about 1000 hPa, but the second day was 500 hPa until the end of the month was 33 hPa, but the first day of the next month was 1000 hPa again. I would like to ask what is the reason for this. If I want to check the column average concentration of 815 hPa-215 hPa at the transit time of a certain pollutant every day, how can I achieve it?
Thank you for your help and reply

**Comment by msulprizio** [comment] 2024-09-26 15:29
This is a duplicate of [Satellite diagnostic simulations show a gradual decrease in pressure day by day #2466](https://github.com/geoschem/geos-chem/issues/2466).

**Closed by msulprizio** 2024-09-26 15:29 UTC
Labels: category: Question, duplicate
