### ISSUE TITLE
a strange problem, when the dryrun process

### ISSUE THREAD

**Issue by rongbing0353** [geoschem/geos-chem#2620] opened 2024-12-09 02:38 UTC
### Your name

runbin zhang

### Your affiliation

lanzhou university

### Please provide a clear and concise description of your question or discussion topic.

I have downloaded the data which are required, but , erro happens, It can't find some files

**Comment by rongbing0353** [comment] 2024-12-09 02:47
<img width="551" alt="微信图片_20241209104552" src="https://github.com/user-attachments/assets/c48cb10e-7379-41c2-b244-981c7a70369e">
<img width="482" alt="微信图片_20241209104620" src="https://github.com/user-attachments/assets/75dc7409-5fc4-4885-9802-7b578c6dead6">

**Comment by rongbing0353** [comment] 2024-12-09 02:49
<img width="551" alt="微信图片_20241209104552" src="https://github.com/user-attachments/assets/014b9bd9-16dd-44d7-b326-b023e479e87a">
<img width="482" alt="微信图片_20241209104620" src="https://github.com/user-attachments/assets/124c7621-8d56-4fdf-97dc-68cd641fe0bc">

**Comment by yantosca** [comment] 2024-12-09 18:34
Thanks for writing @rongbing0353.  Please see a workaround in issue #2594.

We recommend that you do a search for similar issues before reporting a new issue.  It may happen that someone has reported the issue previously.

**Comment by yantosca** [comment] 2024-12-09 18:34
This is a duplicate of #2594.

**Comment by yantosca** [comment] 2024-12-11 15:52
Closing out this issue

**Closed by yantosca** 2024-12-11 15:52 UTC
Labels: category: Question, duplicate
