### ISSUE TITLE
Request min/max scale factors for particulate nitrate photolysis in the geoschem_input.yml file

### ISSUE THREAD

**Issue by ktravis213** [geoschem/geos-chem#1966] opened 2023-09-20 11:04 UTC
### Name and Institution (Required)
Name: Katie Travis
Institution: NASA Langley

### New GEOS-Chem feature or discussion

Request to add in a min and max scaling factor in the geoschem_input.yml for calculating the frequency of particulate nitrate photolysis.  This will allow users to easily adjust the rate in remote and urban locations without having to recompile the model, in a similar manner as is currently done for HO2 uptake, another uncertain process. This was discussed at the GCSC meeting on 9/19 with @barronh

**Comment by barronh** [comment] 2023-09-21 10:30
@yantosca, @msulprizio, and Viral pointed me to the current capabilities. Right now

* Lines L668 and L671 in the dev code calculates a factor `FAC = max(SSA / (SSA + NO3), .1)`
* Lines L687 and L688 apply a scaling factor `JscaleNIT` to that `FAC`. 

When `JscaleNIT = 100` (the default), this is consistent with Viral's paper `EF = max(100 * SSA / (SSA + NO3), 10)`.[2] The `JscaleNIT` and `JscaleNITs` are read from the yaml file, which allows the user to scale the whole range together (e.g., 10 to 100 or 5 to 50 or 100 to 1000).

Is this what you were asking for? Or were you asking to scale the min and max independently?

[1] https://github.com/geoschem/geos-chem/blob/dev/14.2.1/GeosCore/photolysis_mod.F90#L667-L688
[2] https://doi.org/10.5194/acp-23-1227-2023

**Comment by barronh** [comment] 2023-09-21 10:31
p.s., I couldn't find Viral's github tag. I'll edit the post to add him if I find it.

**Comment by barronh** [comment] 2023-09-21 10:46
I forgot to mentions that the `JscaleNIT` (and `JscaleNITs`) can be traced back via `hvAerNIT_JNIT` (and `hvAerNIT_JNITs`) to the yaml file variable `NIT_Jscale_JHNO2`  (and `NITs_Jscale_JHNO3`) in the `photolyze_nitrate_aerosol` subsection of the yaml.[1]

Both the NIT and NITs species photolyze to NO2 and HNO2, so I am a little confused by the name of the scaling parameter for NITs (`NITs_Jscale_JHNO3`).

[1] https://github.com/geoschem/geos-chem/blob/dev/14.2.1/run/GCClassic/geoschem_config.yml.templates/geoschem_config.yml.fullchem#L97-L102

**Comment by yantosca** [comment] 2023-09-22 14:34
I would defer to @viral211 as for the naming scheme.  I believe the YAML tags are the same names as in the code.

**Comment by viral211** [comment] 2023-09-22 15:03
I agree with @barronh, that the names of the YAML tags are confusing. It would be better to call them `NITs_Jscale` and `NIT_Jscale` since they are mapped to `Input_Opt%hvAerNIT_JNITs` and `Input_Opt%hvAerNIT_JNIT` in the code.

**Comment by yantosca** [comment] 2023-09-22 15:04
Thanks @viral211 and @barronh.  I can make a feature request to change those for 14.3.0.  Simple update but we should do it in a feature version and not a bugfix version.

**Comment by yantosca** [comment] 2024-06-06 13:59
@barronh @ktravis213: Is this issue now resolved?

**Comment by barronh** [comment] 2024-06-10 23:21
@yantosca I see the change in the run https://github.com/geoschem/geos-chem/tree/main/run/GCClassic/geoschem_config.yml.templates, so I suspect that it is. I haven't run this version, but I assume it works.

**Comment by yantosca** [comment] 2024-10-07 21:54
Closing out this issue.

**Closed by yantosca** 2024-10-07 21:54 UTC
Labels: category: Feature Request, topic: Chemical Mechanisms
