### ISSUE TITLE
Cannot use ONLINE SULFUR AEROSOLS if LSULF=F!

### ISSUE THREAD

**Issue by yonghumu** [geoschem/geos-chem#2579] opened 2024-11-20 19:12 UTC
### Your name

Liu Meng

### Your affiliation

LZU

### What happened? What did you expect to happen?
```console
===============================================================================
GEOS-Chem ERROR: Cannot use ONLINE SULFUR AEROSOLS if LSULF=F!
-> at Do_Error_Checks (in GeosCore/input_mod.F90)
===============================================================================

===============================================================================
GEOS-Chem ERROR: Error encountered in "Do_Error_Checks"!
 -> at GC_Init_Extra (in module GeosCore/gc_environment_mod.F90)
===============================================================================

===============================================================================
GEOS-CHEM ERROR: Error encountered in "GC_Init_Extra"!
STOP at  -> at GEOS-Chem (in GeosCore/main.F90)
===============================================================================
```

### What are the steps to reproduce the bug?

Want to close the chemistry module and run

### Please attach any relevant configuration and log files.

[input (1).geos.txt](https://github.com/user-attachments/files/17835592/input.1.geos.txt)

### What GEOS-Chem version were you using?

13.0.0

### What environment were you running GEOS-Chem on?

Local cluster

### What compiler and version were you using?

gcc 10.2.0

### Will you be addressing this bug yourself?

No

### In what configuration were you running GEOS-Chem?

GCClassic

### What simulation were you running?

Full chemistry

### As what resolution were you running GEOS-Chem?

2×2.5

### What meterology fields did you use?

MERRA-2

**Comment by yantosca** [comment] 2024-11-20 19:32
Thanks for writing.  The issue is that you have in `input.geos`:
```console
Online SULFATE AEROSOLS : F
```
but you also have:
```console
Species name            : SO2
```
which is a sulfate species.  Try removing that from the list of species and rerunning.

Also note: 13.0.0 is by now an unsupported version.  Please update to the latest version when possible.

**Comment by yantosca** [comment] 2024-11-20 20:13
@yonghumu: Could you post your complete GEOS-Chem log file?  

Also, are you able to run an "out-of-the-box" (i.e. unmodified) aerosol-only simulation?

**Comment by yonghumu** [comment] 2024-11-20 20:19
[GC.log.txt](https://github.com/user-attachments/files/17836275/GC.log.txt)

Do you mean to select the aerosol-only option at installation and then run？

**Comment by yantosca** [comment] 2024-11-21 15:23
That's correct @yonghumu.  The problem is that you are trying to run an aerosol-only simulation from within a fullchem run directory.  From your GC.log:

```console
Simulation name             : fullchem

... etc ...

ADVECTED SPECIES MENU
------------------------------------------------
  #  Species Name
  1  BCPI                           
  2  BCPO                           
  3  CH4                            
  4  CLOCK                          
  5  CO                             
  6  DST1                           
  7  DST2                           
  8  DST3                           
  9  DST4                           
 10  H2O                            
 11  NH3                            
 12  NH4                            
 13  NO                             
 14  NO2                            
 15  O3                             
 16  OCPI                           
 17  OCPO                           
 18  SALA                           
 19  SALAAL                         
 20  SALC                           
 21  SALCAL                         
```

**Comment by yantosca** [comment] 2024-12-17 16:36
I am closing out this issue as version 13 is no longer supported

**Closed by yantosca** 2024-12-17 16:36 UTC
Labels: category: Bug, topic: Configuration Files, unsupported version, topic: Aerosols
