### ISSUE TITLE
[BUG/ISSUE] GMAO_TEMP from planeflight diagnostic appears wrong

### ISSUE THREAD

**Issue by tscarter** [geoschem/geos-chem#898] opened 2021-09-17 18:24 UTC
### Description of the problem
The temperature variable (GMAO_TEMP) outputted in the planeflight diagnostic appears to be wrong because it gives values as low as ~200K at times. I've run it for KORUS (~May-June 2016), ATOM-1 (July-Aug 2016), FIREX (July-Sep 2019), and as a tower diagnostic for the Amazon Tall Tower Observation (ATTO) in June and September 2019 and see the strangely low values.

### Description of troubleshooting performed
I've checked the actual MERRA-2 files, and those give reasonable values closer to 300K. I've also checked the monthly netcdf output, which also looks fine, and I've run an hourly simulation to check hourly netcdf output, which also looks fine. 

So by process of elimination, it seems like a problem specifically with the temperature field output in the planeflight diagnostic, but I'm not where that error is coming from. I've attached one planeflight file for reference. Any ideas would be appreciated!

### GEOS-Chem version
13.0.0

### Description of modifications
None that should affect this I think

### Log files
- Build log (if applicable):
- Run logs (if applicable):
[plane.log.20190615.pdf](https://github.com/geoschem/geos-chem/files/7187679/plane.log.20190615.pdf)

- Run script (if applicable):

### Software versions
- CMake version:
- Compilers (Intel or GNU, and version):
- NetCDF version:

**Comment by yantosca** [comment] 2021-09-20 13:39
Thanks @tscarter, we will take a look at this.  I believe the planeflight diagnostic uses the State_Met%T field so it should be the same temperature as is read in/interpolated.  But there may be something else going on here.  Stay tuned.

**Comment by yantosca** [comment] 2021-09-20 21:04
Hi @tscarter, I made a test Planeflight.dat file for 20190701 (since that is the date of the restart file that ships with the fullchem run directories):
```
Planeflight.dat -- Input file for planeflight diagnostic
GCST
July 2018
-----------------------------------------------------------
1      <-- # of variables to be output (listed below)
-----------------------------------------------------------
GMAO_TEMP
-----------------------------------------------------------
  Now give the times and locations of the flight
-----------------------------------------------------------
Point   Type DD-MM-YYYY HH:MM     LAT     LON ALT/PRE  OBS
    1   Tamt 01-07-2019 00:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 01:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 02:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 03:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 04:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 05:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 06:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 07:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 08:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 09:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 09:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 10:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 11:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 12:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 13:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 14:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 15:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 16:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 17:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 18:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 19:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 20:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 21:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 22:00  -59.01   -2.15    30.0
    1   Tamt 01-07-2019 23:00  -59.01   -2.15    30.0
99999   END  00-00-0000 00:00    0.00    0.00    0.00  0.000
```
and this gives output:
```
POINT    TYPE YYYYMMDD HHMM     LAT     LON   PRESS        OBS     T-IND P-I I-IND J-IND  GMAO_TEMP 
    1    Tamt 20190701 0000  -59.01   -2.15  970.51      0.000 000000001 001 00037 00009  2.707E+002
    2    Tamt 20190701 0100  -59.01   -2.15  970.51      0.000 000000007 001 00037 00009  2.704E+002
    3    Tamt 20190701 0200  -59.01   -2.15  970.51      0.000 000000013 001 00037 00009  2.701E+002
    4    Tamt 20190701 0300  -59.01   -2.15  970.51      0.000 000000019 001 00037 00009  2.698E+002
    5    Tamt 20190701 0400  -59.01   -2.15  970.51      0.000 000000025 001 00037 00009  2.696E+002
    6    Tamt 20190701 0500  -59.01   -2.15  970.51      0.000 000000031 001 00037 00009  2.694E+002
    7    Tamt 20190701 0600  -59.01   -2.15  970.51      0.000 000000037 001 00037 00009  2.692E+002
    8    Tamt 20190701 0700  -59.01   -2.15  970.51      0.000 000000043 001 00037 00009  2.688E+002
    9    Tamt 20190701 0800  -59.01   -2.15  970.51      0.000 000000049 001 00037 00009  2.685E+002
   10    Tamt 20190701 0900  -59.01   -2.15  970.51      0.000 000000055 001 00037 00009  2.681E+002
   11    Tamt 20190701 0900  -59.01   -2.15  970.51      0.000 000000055 001 00037 00009  2.681E+002
   12    Tamt 20190701 1000  -59.01   -2.15  970.51      0.000 000000061 001 00037 00009  2.677E+002
   13    Tamt 20190701 1100  -59.01   -2.15  970.51      0.000 000000067 001 00037 00009  2.674E+002
   14    Tamt 20190701 1200  -59.01   -2.15  970.51      0.000 000000073 001 00037 00009  2.670E+002
   15    Tamt 20190701 1300  -59.01   -2.15  970.51      0.000 000000079 001 00037 00009  2.665E+002
   16    Tamt 20190701 1400  -59.01   -2.15  970.51      0.000 000000085 001 00037 00009  2.659E+002
   17    Tamt 20190701 1500  -59.01   -2.15  970.51      0.000 000000091 001 00037 00009  2.654E+002
   18    Tamt 20190701 1600  -59.01   -2.15  970.51      0.000 000000097 001 00037 00009  2.646E+002
   19    Tamt 20190701 1700  -59.01   -2.15  970.51      0.000 000000103 001 00037 00009  2.638E+002
   20    Tamt 20190701 1800  -59.01   -2.15  970.51      0.000 000000109 001 00037 00009  2.631E+002
   21    Tamt 20190701 1900  -59.01   -2.15  970.51      0.000 000000115 001 00037 00009  2.626E+002
   22    Tamt 20190701 2000  -59.01   -2.15  970.51      0.000 000000121 001 00037 00009  2.622E+002
   23    Tamt 20190701 2100  -59.01   -2.15  970.51      0.000 000000127 001 00037 00009  2.618E+002
```
I looked up lat=-59.01 and lon = -2.15, and it's in the Southern Ocean.
![2021_09_20_16_57_54_Greenshot](https://user-images.githubusercontent.com/5880296/134074960-c7dfcef8-0188-476b-81e4-857b225fff85.png)

So the planeflight temperature ranges from 270K to 261K (-5C to -10C), which is probably not unreasonable for that latitude in SH winter.

Do you have the coordinates of a grid box where it goes to -100C?  I can try to reproduce.  I'd like to make sure it's not an issue with e.g. interpolation of pressure to altitude -- if Planeflight is grabbing a box higher up in the atmosphere than it should be.

**Comment by tscarter** [comment] 2021-09-20 21:42
Thanks for checking! I really appreciate it.

After more digging, it appears to be an issue on my end and not with the
model. So we can close out the issue.

**Comment by yantosca** [comment] 2021-09-20 22:10
Thanks @tscarter!  Will close this out.  Glad you found the error!

**Closed by yantosca** 2021-09-20 22:10 UTC
Labels: bug, diagnostics
