### ISSUE TITLE
[BUG/ISSUE] Error in GEOS-FP temperature field on 2021-04-04

### ISSUE THREAD

**Issue by XueyingYu-1993** [geoschem/geos-chem#1397] opened 2022-09-22 06:40 UTC
The temperature of GEOS-FP in some files of 2021 and 2022 have errors as follows. This will return NA for the simulations and stop the model directly.
![image](https://user-images.githubusercontent.com/77073047/191675892-9c0775e3-1846-4320-b6c9-8dfd82ffe773.png)

**Comment by msulprizio** [comment] 2022-09-22 13:49
Thank you for reporting this. Do you have a list of dates you could provide? Did you notice this error in the 4x5 or 2x2.5 files or both?

@Jourdan-He or @SaptSinha could you check these files at WashU? It may be good to check all resolutions (including nested) just in case. Any files with bad fields will need to be reprocessed.

**Comment by XueyingYu-1993** [comment] 2022-09-22 18:47
This error is in 4x5. Sorry I do not have a list of the date.

**Comment by yantosca** [comment] 2022-09-22 20:01
I've confirmed that the GEOSFP.20210404.I3.4x5.nc data file has corrupted data.  These might have to be recreated at WashU. 
 Tagging @Jourdan-He and @SaptSinha.

**Comment by yantosca** [comment] 2022-09-22 20:03
Also this corrupted data is the root cause of issue #1337.

**Comment by Jourdan-He** [comment] 2022-09-23 18:25
I downloaded the GEOSFP.20210404.I3.4x5.nc file from ExtData and the plot seems normal to me.
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/59769352/192032917-71e9d687-f4df-4f29-b6a9-f47134d492f2.png">

**Comment by yantosca** [comment] 2022-09-23 22:27
Thanks @Jourdan-He  So we may need to redownload it on this end.  I can do that.

**Comment by XueyingYu-1993** [comment] 2022-09-23 23:29
Thanks @Jourdan-He Could you please let me know where is the ExtData folder? I can only find GEOS_4x5/GEOS_FP folder at WashU (using globus to transfer files).

**Comment by yantosca** [comment] 2022-09-26 13:00
@XueyingYu-1993, at the geoschemdata.wustl.edu folder, the root directory is the same as the ExtData folder.  So the path GEOS_4x5/GEOS_FP would be correct.

**Comment by yantosca** [comment] 2022-09-28 20:46
I will close out this issue.  It is resolved with a re-downloading of the data.

**Closed by yantosca** 2022-09-28 20:46 UTC
Labels: bug, data sources / I-O
