### ISSUE TITLE
[QUESTION] Is SOAGX part of biogenic secondary organic aerosol?

### ISSUE THREAD

**Issue by dxy8413** [geoschem/geos-chem#876] opened 2021-09-01 05:18 UTC
### Ask a question about GEOS-Chem:
Is SOAGX part of biogenic secondary organic aerosol? It seems the variable "TotalBiogenicOA" equals to the sum of SOAIE, SOATP, SOAGX, and LVOCOA. But in urban areas, SOAGX may be mostly from anthropogenic aromatics.

**Comment by msulprizio** [comment] 2021-09-01 15:37
This is a duplicate of https://github.com/geoschem/geos-chem/issues/848. I will close this issue and move the conversation there.

**Closed by msulprizio** 2021-09-01 15:37 UTC
Labels: question, duplicate
